//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEB.integracionSR {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://intec.edu.do", ConfigurationName="integracionSR.integracionSWSoap")]
    public interface integracionSWSoap {
        
        // CODEGEN: Generating message contract since element name codigo from namespace http://intec.edu.do is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://intec.edu.do/InsertarProductoINTEGRACION", ReplyAction="*")]
        WEB.integracionSR.InsertarProductoINTEGRACIONResponse InsertarProductoINTEGRACION(WEB.integracionSR.InsertarProductoINTEGRACIONRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://intec.edu.do/InsertarProductoINTEGRACION", ReplyAction="*")]
        System.Threading.Tasks.Task<WEB.integracionSR.InsertarProductoINTEGRACIONResponse> InsertarProductoINTEGRACIONAsync(WEB.integracionSR.InsertarProductoINTEGRACIONRequest request);
        
        // CODEGEN: Generating message contract since element name codigo from namespace http://intec.edu.do is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://intec.edu.do/DeleteProductoINTEGRACION", ReplyAction="*")]
        WEB.integracionSR.DeleteProductoINTEGRACIONResponse DeleteProductoINTEGRACION(WEB.integracionSR.DeleteProductoINTEGRACIONRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://intec.edu.do/DeleteProductoINTEGRACION", ReplyAction="*")]
        System.Threading.Tasks.Task<WEB.integracionSR.DeleteProductoINTEGRACIONResponse> DeleteProductoINTEGRACIONAsync(WEB.integracionSR.DeleteProductoINTEGRACIONRequest request);
        
        // CODEGEN: Generating message contract since element name codigo from namespace http://intec.edu.do is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://intec.edu.do/UpdateProductoINTEGRACION", ReplyAction="*")]
        WEB.integracionSR.UpdateProductoINTEGRACIONResponse UpdateProductoINTEGRACION(WEB.integracionSR.UpdateProductoINTEGRACIONRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://intec.edu.do/UpdateProductoINTEGRACION", ReplyAction="*")]
        System.Threading.Tasks.Task<WEB.integracionSR.UpdateProductoINTEGRACIONResponse> UpdateProductoINTEGRACIONAsync(WEB.integracionSR.UpdateProductoINTEGRACIONRequest request);
        
        // CODEGEN: Generating message contract since element name Nombres from namespace http://intec.edu.do is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://intec.edu.do/InsertClienteINTEGRACION", ReplyAction="*")]
        WEB.integracionSR.InsertClienteINTEGRACIONResponse InsertClienteINTEGRACION(WEB.integracionSR.InsertClienteINTEGRACIONRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://intec.edu.do/InsertClienteINTEGRACION", ReplyAction="*")]
        System.Threading.Tasks.Task<WEB.integracionSR.InsertClienteINTEGRACIONResponse> InsertClienteINTEGRACIONAsync(WEB.integracionSR.InsertClienteINTEGRACIONRequest request);
        
        // CODEGEN: Generating message contract since element name Cedula from namespace http://intec.edu.do is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://intec.edu.do/DeleteClienteINTEGRACION", ReplyAction="*")]
        WEB.integracionSR.DeleteClienteINTEGRACIONResponse DeleteClienteINTEGRACION(WEB.integracionSR.DeleteClienteINTEGRACIONRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://intec.edu.do/DeleteClienteINTEGRACION", ReplyAction="*")]
        System.Threading.Tasks.Task<WEB.integracionSR.DeleteClienteINTEGRACIONResponse> DeleteClienteINTEGRACIONAsync(WEB.integracionSR.DeleteClienteINTEGRACIONRequest request);
        
        // CODEGEN: Generating message contract since element name Cedula from namespace http://intec.edu.do is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://intec.edu.do/UpdateClienteINTEGRACION", ReplyAction="*")]
        WEB.integracionSR.UpdateClienteINTEGRACIONResponse UpdateClienteINTEGRACION(WEB.integracionSR.UpdateClienteINTEGRACIONRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://intec.edu.do/UpdateClienteINTEGRACION", ReplyAction="*")]
        System.Threading.Tasks.Task<WEB.integracionSR.UpdateClienteINTEGRACIONResponse> UpdateClienteINTEGRACIONAsync(WEB.integracionSR.UpdateClienteINTEGRACIONRequest request);
        
        // CODEGEN: Generating message contract since element name Nombres from namespace http://intec.edu.do is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://intec.edu.do/InsertEmpleadoINTEGRACION", ReplyAction="*")]
        WEB.integracionSR.InsertEmpleadoINTEGRACIONResponse InsertEmpleadoINTEGRACION(WEB.integracionSR.InsertEmpleadoINTEGRACIONRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://intec.edu.do/InsertEmpleadoINTEGRACION", ReplyAction="*")]
        System.Threading.Tasks.Task<WEB.integracionSR.InsertEmpleadoINTEGRACIONResponse> InsertEmpleadoINTEGRACIONAsync(WEB.integracionSR.InsertEmpleadoINTEGRACIONRequest request);
        
        // CODEGEN: Generating message contract since element name Cedula from namespace http://intec.edu.do is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://intec.edu.do/DeleteEmpleadoINTEGRACION", ReplyAction="*")]
        WEB.integracionSR.DeleteEmpleadoINTEGRACIONResponse DeleteEmpleadoINTEGRACION(WEB.integracionSR.DeleteEmpleadoINTEGRACIONRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://intec.edu.do/DeleteEmpleadoINTEGRACION", ReplyAction="*")]
        System.Threading.Tasks.Task<WEB.integracionSR.DeleteEmpleadoINTEGRACIONResponse> DeleteEmpleadoINTEGRACIONAsync(WEB.integracionSR.DeleteEmpleadoINTEGRACIONRequest request);
        
        // CODEGEN: Generating message contract since element name Cedula from namespace http://intec.edu.do is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://intec.edu.do/UpdateEmpleadoINTEGRACION", ReplyAction="*")]
        WEB.integracionSR.UpdateEmpleadoINTEGRACIONResponse UpdateEmpleadoINTEGRACION(WEB.integracionSR.UpdateEmpleadoINTEGRACIONRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://intec.edu.do/UpdateEmpleadoINTEGRACION", ReplyAction="*")]
        System.Threading.Tasks.Task<WEB.integracionSR.UpdateEmpleadoINTEGRACIONResponse> UpdateEmpleadoINTEGRACIONAsync(WEB.integracionSR.UpdateEmpleadoINTEGRACIONRequest request);
        
        // CODEGEN: Generating message contract since element name Nombres from namespace http://intec.edu.do is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://intec.edu.do/InsertCuentaINTEGRACION", ReplyAction="*")]
        WEB.integracionSR.InsertCuentaINTEGRACIONResponse InsertCuentaINTEGRACION(WEB.integracionSR.InsertCuentaINTEGRACIONRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://intec.edu.do/InsertCuentaINTEGRACION", ReplyAction="*")]
        System.Threading.Tasks.Task<WEB.integracionSR.InsertCuentaINTEGRACIONResponse> InsertCuentaINTEGRACIONAsync(WEB.integracionSR.InsertCuentaINTEGRACIONRequest request);
        
        // CODEGEN: Generating message contract since element name cuentaID from namespace http://intec.edu.do is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://intec.edu.do/DeleteCuentaINTEGRACION", ReplyAction="*")]
        WEB.integracionSR.DeleteCuentaINTEGRACIONResponse DeleteCuentaINTEGRACION(WEB.integracionSR.DeleteCuentaINTEGRACIONRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://intec.edu.do/DeleteCuentaINTEGRACION", ReplyAction="*")]
        System.Threading.Tasks.Task<WEB.integracionSR.DeleteCuentaINTEGRACIONResponse> DeleteCuentaINTEGRACIONAsync(WEB.integracionSR.DeleteCuentaINTEGRACIONRequest request);
        
        // CODEGEN: Generating message contract since element name Nombres from namespace http://intec.edu.do is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://intec.edu.do/InsertFacturaINTEGRACION", ReplyAction="*")]
        WEB.integracionSR.InsertFacturaINTEGRACIONResponse InsertFacturaINTEGRACION(WEB.integracionSR.InsertFacturaINTEGRACIONRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://intec.edu.do/InsertFacturaINTEGRACION", ReplyAction="*")]
        System.Threading.Tasks.Task<WEB.integracionSR.InsertFacturaINTEGRACIONResponse> InsertFacturaINTEGRACIONAsync(WEB.integracionSR.InsertFacturaINTEGRACIONRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertarProductoINTEGRACIONRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertarProductoINTEGRACION", Namespace="http://intec.edu.do", Order=0)]
        public WEB.integracionSR.InsertarProductoINTEGRACIONRequestBody Body;
        
        public InsertarProductoINTEGRACIONRequest() {
        }
        
        public InsertarProductoINTEGRACIONRequest(WEB.integracionSR.InsertarProductoINTEGRACIONRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://intec.edu.do")]
    public partial class InsertarProductoINTEGRACIONRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string codigo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string marca;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public decimal precio;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int cantidad;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string tipo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string nombre;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public int peso;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string imagen;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string descripcion;
        
        public InsertarProductoINTEGRACIONRequestBody() {
        }
        
        public InsertarProductoINTEGRACIONRequestBody(string codigo, string marca, decimal precio, int cantidad, string tipo, string nombre, int peso, string imagen, string descripcion) {
            this.codigo = codigo;
            this.marca = marca;
            this.precio = precio;
            this.cantidad = cantidad;
            this.tipo = tipo;
            this.nombre = nombre;
            this.peso = peso;
            this.imagen = imagen;
            this.descripcion = descripcion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertarProductoINTEGRACIONResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertarProductoINTEGRACIONResponse", Namespace="http://intec.edu.do", Order=0)]
        public WEB.integracionSR.InsertarProductoINTEGRACIONResponseBody Body;
        
        public InsertarProductoINTEGRACIONResponse() {
        }
        
        public InsertarProductoINTEGRACIONResponse(WEB.integracionSR.InsertarProductoINTEGRACIONResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://intec.edu.do")]
    public partial class InsertarProductoINTEGRACIONResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string InsertarProductoINTEGRACIONResult;
        
        public InsertarProductoINTEGRACIONResponseBody() {
        }
        
        public InsertarProductoINTEGRACIONResponseBody(string InsertarProductoINTEGRACIONResult) {
            this.InsertarProductoINTEGRACIONResult = InsertarProductoINTEGRACIONResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteProductoINTEGRACIONRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteProductoINTEGRACION", Namespace="http://intec.edu.do", Order=0)]
        public WEB.integracionSR.DeleteProductoINTEGRACIONRequestBody Body;
        
        public DeleteProductoINTEGRACIONRequest() {
        }
        
        public DeleteProductoINTEGRACIONRequest(WEB.integracionSR.DeleteProductoINTEGRACIONRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://intec.edu.do")]
    public partial class DeleteProductoINTEGRACIONRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string codigo;
        
        public DeleteProductoINTEGRACIONRequestBody() {
        }
        
        public DeleteProductoINTEGRACIONRequestBody(string codigo) {
            this.codigo = codigo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteProductoINTEGRACIONResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteProductoINTEGRACIONResponse", Namespace="http://intec.edu.do", Order=0)]
        public WEB.integracionSR.DeleteProductoINTEGRACIONResponseBody Body;
        
        public DeleteProductoINTEGRACIONResponse() {
        }
        
        public DeleteProductoINTEGRACIONResponse(WEB.integracionSR.DeleteProductoINTEGRACIONResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://intec.edu.do")]
    public partial class DeleteProductoINTEGRACIONResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string DeleteProductoINTEGRACIONResult;
        
        public DeleteProductoINTEGRACIONResponseBody() {
        }
        
        public DeleteProductoINTEGRACIONResponseBody(string DeleteProductoINTEGRACIONResult) {
            this.DeleteProductoINTEGRACIONResult = DeleteProductoINTEGRACIONResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateProductoINTEGRACIONRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateProductoINTEGRACION", Namespace="http://intec.edu.do", Order=0)]
        public WEB.integracionSR.UpdateProductoINTEGRACIONRequestBody Body;
        
        public UpdateProductoINTEGRACIONRequest() {
        }
        
        public UpdateProductoINTEGRACIONRequest(WEB.integracionSR.UpdateProductoINTEGRACIONRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://intec.edu.do")]
    public partial class UpdateProductoINTEGRACIONRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string codigo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string usuarioCedula;
        
        public UpdateProductoINTEGRACIONRequestBody() {
        }
        
        public UpdateProductoINTEGRACIONRequestBody(string codigo, string usuarioCedula) {
            this.codigo = codigo;
            this.usuarioCedula = usuarioCedula;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateProductoINTEGRACIONResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateProductoINTEGRACIONResponse", Namespace="http://intec.edu.do", Order=0)]
        public WEB.integracionSR.UpdateProductoINTEGRACIONResponseBody Body;
        
        public UpdateProductoINTEGRACIONResponse() {
        }
        
        public UpdateProductoINTEGRACIONResponse(WEB.integracionSR.UpdateProductoINTEGRACIONResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://intec.edu.do")]
    public partial class UpdateProductoINTEGRACIONResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UpdateProductoINTEGRACIONResult;
        
        public UpdateProductoINTEGRACIONResponseBody() {
        }
        
        public UpdateProductoINTEGRACIONResponseBody(string UpdateProductoINTEGRACIONResult) {
            this.UpdateProductoINTEGRACIONResult = UpdateProductoINTEGRACIONResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertClienteINTEGRACIONRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertClienteINTEGRACION", Namespace="http://intec.edu.do", Order=0)]
        public WEB.integracionSR.InsertClienteINTEGRACIONRequestBody Body;
        
        public InsertClienteINTEGRACIONRequest() {
        }
        
        public InsertClienteINTEGRACIONRequest(WEB.integracionSR.InsertClienteINTEGRACIONRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://intec.edu.do")]
    public partial class InsertClienteINTEGRACIONRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Nombres;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Apellidos;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Cedula;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Telefono;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public System.DateTime fechaNacimiento;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Email;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string Password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string Sexo;
        
        public InsertClienteINTEGRACIONRequestBody() {
        }
        
        public InsertClienteINTEGRACIONRequestBody(string Nombres, string Apellidos, string Cedula, string Telefono, System.DateTime fechaNacimiento, string Email, string Password, string Sexo) {
            this.Nombres = Nombres;
            this.Apellidos = Apellidos;
            this.Cedula = Cedula;
            this.Telefono = Telefono;
            this.fechaNacimiento = fechaNacimiento;
            this.Email = Email;
            this.Password = Password;
            this.Sexo = Sexo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertClienteINTEGRACIONResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertClienteINTEGRACIONResponse", Namespace="http://intec.edu.do", Order=0)]
        public WEB.integracionSR.InsertClienteINTEGRACIONResponseBody Body;
        
        public InsertClienteINTEGRACIONResponse() {
        }
        
        public InsertClienteINTEGRACIONResponse(WEB.integracionSR.InsertClienteINTEGRACIONResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://intec.edu.do")]
    public partial class InsertClienteINTEGRACIONResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string InsertClienteINTEGRACIONResult;
        
        public InsertClienteINTEGRACIONResponseBody() {
        }
        
        public InsertClienteINTEGRACIONResponseBody(string InsertClienteINTEGRACIONResult) {
            this.InsertClienteINTEGRACIONResult = InsertClienteINTEGRACIONResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteClienteINTEGRACIONRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteClienteINTEGRACION", Namespace="http://intec.edu.do", Order=0)]
        public WEB.integracionSR.DeleteClienteINTEGRACIONRequestBody Body;
        
        public DeleteClienteINTEGRACIONRequest() {
        }
        
        public DeleteClienteINTEGRACIONRequest(WEB.integracionSR.DeleteClienteINTEGRACIONRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://intec.edu.do")]
    public partial class DeleteClienteINTEGRACIONRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Cedula;
        
        public DeleteClienteINTEGRACIONRequestBody() {
        }
        
        public DeleteClienteINTEGRACIONRequestBody(string Cedula) {
            this.Cedula = Cedula;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteClienteINTEGRACIONResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteClienteINTEGRACIONResponse", Namespace="http://intec.edu.do", Order=0)]
        public WEB.integracionSR.DeleteClienteINTEGRACIONResponseBody Body;
        
        public DeleteClienteINTEGRACIONResponse() {
        }
        
        public DeleteClienteINTEGRACIONResponse(WEB.integracionSR.DeleteClienteINTEGRACIONResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://intec.edu.do")]
    public partial class DeleteClienteINTEGRACIONResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string DeleteClienteINTEGRACIONResult;
        
        public DeleteClienteINTEGRACIONResponseBody() {
        }
        
        public DeleteClienteINTEGRACIONResponseBody(string DeleteClienteINTEGRACIONResult) {
            this.DeleteClienteINTEGRACIONResult = DeleteClienteINTEGRACIONResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateClienteINTEGRACIONRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateClienteINTEGRACION", Namespace="http://intec.edu.do", Order=0)]
        public WEB.integracionSR.UpdateClienteINTEGRACIONRequestBody Body;
        
        public UpdateClienteINTEGRACIONRequest() {
        }
        
        public UpdateClienteINTEGRACIONRequest(WEB.integracionSR.UpdateClienteINTEGRACIONRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://intec.edu.do")]
    public partial class UpdateClienteINTEGRACIONRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public decimal totalGastado;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Cedula;
        
        public UpdateClienteINTEGRACIONRequestBody() {
        }
        
        public UpdateClienteINTEGRACIONRequestBody(decimal totalGastado, string Cedula) {
            this.totalGastado = totalGastado;
            this.Cedula = Cedula;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateClienteINTEGRACIONResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateClienteINTEGRACIONResponse", Namespace="http://intec.edu.do", Order=0)]
        public WEB.integracionSR.UpdateClienteINTEGRACIONResponseBody Body;
        
        public UpdateClienteINTEGRACIONResponse() {
        }
        
        public UpdateClienteINTEGRACIONResponse(WEB.integracionSR.UpdateClienteINTEGRACIONResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://intec.edu.do")]
    public partial class UpdateClienteINTEGRACIONResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UpdateClienteINTEGRACIONResult;
        
        public UpdateClienteINTEGRACIONResponseBody() {
        }
        
        public UpdateClienteINTEGRACIONResponseBody(string UpdateClienteINTEGRACIONResult) {
            this.UpdateClienteINTEGRACIONResult = UpdateClienteINTEGRACIONResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertEmpleadoINTEGRACIONRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertEmpleadoINTEGRACION", Namespace="http://intec.edu.do", Order=0)]
        public WEB.integracionSR.InsertEmpleadoINTEGRACIONRequestBody Body;
        
        public InsertEmpleadoINTEGRACIONRequest() {
        }
        
        public InsertEmpleadoINTEGRACIONRequest(WEB.integracionSR.InsertEmpleadoINTEGRACIONRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://intec.edu.do")]
    public partial class InsertEmpleadoINTEGRACIONRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Nombres;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Apellidos;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Cedula;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Telefono;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string rol;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Email;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string Password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string Sexo;
        
        public InsertEmpleadoINTEGRACIONRequestBody() {
        }
        
        public InsertEmpleadoINTEGRACIONRequestBody(string Nombres, string Apellidos, string Cedula, string Telefono, string rol, string Email, string Password, string Sexo) {
            this.Nombres = Nombres;
            this.Apellidos = Apellidos;
            this.Cedula = Cedula;
            this.Telefono = Telefono;
            this.rol = rol;
            this.Email = Email;
            this.Password = Password;
            this.Sexo = Sexo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertEmpleadoINTEGRACIONResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertEmpleadoINTEGRACIONResponse", Namespace="http://intec.edu.do", Order=0)]
        public WEB.integracionSR.InsertEmpleadoINTEGRACIONResponseBody Body;
        
        public InsertEmpleadoINTEGRACIONResponse() {
        }
        
        public InsertEmpleadoINTEGRACIONResponse(WEB.integracionSR.InsertEmpleadoINTEGRACIONResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://intec.edu.do")]
    public partial class InsertEmpleadoINTEGRACIONResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string InsertEmpleadoINTEGRACIONResult;
        
        public InsertEmpleadoINTEGRACIONResponseBody() {
        }
        
        public InsertEmpleadoINTEGRACIONResponseBody(string InsertEmpleadoINTEGRACIONResult) {
            this.InsertEmpleadoINTEGRACIONResult = InsertEmpleadoINTEGRACIONResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteEmpleadoINTEGRACIONRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteEmpleadoINTEGRACION", Namespace="http://intec.edu.do", Order=0)]
        public WEB.integracionSR.DeleteEmpleadoINTEGRACIONRequestBody Body;
        
        public DeleteEmpleadoINTEGRACIONRequest() {
        }
        
        public DeleteEmpleadoINTEGRACIONRequest(WEB.integracionSR.DeleteEmpleadoINTEGRACIONRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://intec.edu.do")]
    public partial class DeleteEmpleadoINTEGRACIONRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Cedula;
        
        public DeleteEmpleadoINTEGRACIONRequestBody() {
        }
        
        public DeleteEmpleadoINTEGRACIONRequestBody(string Cedula) {
            this.Cedula = Cedula;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteEmpleadoINTEGRACIONResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteEmpleadoINTEGRACIONResponse", Namespace="http://intec.edu.do", Order=0)]
        public WEB.integracionSR.DeleteEmpleadoINTEGRACIONResponseBody Body;
        
        public DeleteEmpleadoINTEGRACIONResponse() {
        }
        
        public DeleteEmpleadoINTEGRACIONResponse(WEB.integracionSR.DeleteEmpleadoINTEGRACIONResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://intec.edu.do")]
    public partial class DeleteEmpleadoINTEGRACIONResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string DeleteEmpleadoINTEGRACIONResult;
        
        public DeleteEmpleadoINTEGRACIONResponseBody() {
        }
        
        public DeleteEmpleadoINTEGRACIONResponseBody(string DeleteEmpleadoINTEGRACIONResult) {
            this.DeleteEmpleadoINTEGRACIONResult = DeleteEmpleadoINTEGRACIONResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateEmpleadoINTEGRACIONRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateEmpleadoINTEGRACION", Namespace="http://intec.edu.do", Order=0)]
        public WEB.integracionSR.UpdateEmpleadoINTEGRACIONRequestBody Body;
        
        public UpdateEmpleadoINTEGRACIONRequest() {
        }
        
        public UpdateEmpleadoINTEGRACIONRequest(WEB.integracionSR.UpdateEmpleadoINTEGRACIONRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://intec.edu.do")]
    public partial class UpdateEmpleadoINTEGRACIONRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int cuentasCobradas;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Cedula;
        
        public UpdateEmpleadoINTEGRACIONRequestBody() {
        }
        
        public UpdateEmpleadoINTEGRACIONRequestBody(int cuentasCobradas, string Cedula) {
            this.cuentasCobradas = cuentasCobradas;
            this.Cedula = Cedula;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateEmpleadoINTEGRACIONResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateEmpleadoINTEGRACIONResponse", Namespace="http://intec.edu.do", Order=0)]
        public WEB.integracionSR.UpdateEmpleadoINTEGRACIONResponseBody Body;
        
        public UpdateEmpleadoINTEGRACIONResponse() {
        }
        
        public UpdateEmpleadoINTEGRACIONResponse(WEB.integracionSR.UpdateEmpleadoINTEGRACIONResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://intec.edu.do")]
    public partial class UpdateEmpleadoINTEGRACIONResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UpdateEmpleadoINTEGRACIONResult;
        
        public UpdateEmpleadoINTEGRACIONResponseBody() {
        }
        
        public UpdateEmpleadoINTEGRACIONResponseBody(string UpdateEmpleadoINTEGRACIONResult) {
            this.UpdateEmpleadoINTEGRACIONResult = UpdateEmpleadoINTEGRACIONResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertCuentaINTEGRACIONRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertCuentaINTEGRACION", Namespace="http://intec.edu.do", Order=0)]
        public WEB.integracionSR.InsertCuentaINTEGRACIONRequestBody Body;
        
        public InsertCuentaINTEGRACIONRequest() {
        }
        
        public InsertCuentaINTEGRACIONRequest(WEB.integracionSR.InsertCuentaINTEGRACIONRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://intec.edu.do")]
    public partial class InsertCuentaINTEGRACIONRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Nombres;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Apellidos;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Producto;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public decimal Total;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string cuentaID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Cedula;
        
        public InsertCuentaINTEGRACIONRequestBody() {
        }
        
        public InsertCuentaINTEGRACIONRequestBody(string Nombres, string Apellidos, string Producto, decimal Total, string cuentaID, string Cedula) {
            this.Nombres = Nombres;
            this.Apellidos = Apellidos;
            this.Producto = Producto;
            this.Total = Total;
            this.cuentaID = cuentaID;
            this.Cedula = Cedula;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertCuentaINTEGRACIONResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertCuentaINTEGRACIONResponse", Namespace="http://intec.edu.do", Order=0)]
        public WEB.integracionSR.InsertCuentaINTEGRACIONResponseBody Body;
        
        public InsertCuentaINTEGRACIONResponse() {
        }
        
        public InsertCuentaINTEGRACIONResponse(WEB.integracionSR.InsertCuentaINTEGRACIONResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://intec.edu.do")]
    public partial class InsertCuentaINTEGRACIONResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string InsertCuentaINTEGRACIONResult;
        
        public InsertCuentaINTEGRACIONResponseBody() {
        }
        
        public InsertCuentaINTEGRACIONResponseBody(string InsertCuentaINTEGRACIONResult) {
            this.InsertCuentaINTEGRACIONResult = InsertCuentaINTEGRACIONResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteCuentaINTEGRACIONRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteCuentaINTEGRACION", Namespace="http://intec.edu.do", Order=0)]
        public WEB.integracionSR.DeleteCuentaINTEGRACIONRequestBody Body;
        
        public DeleteCuentaINTEGRACIONRequest() {
        }
        
        public DeleteCuentaINTEGRACIONRequest(WEB.integracionSR.DeleteCuentaINTEGRACIONRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://intec.edu.do")]
    public partial class DeleteCuentaINTEGRACIONRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string cuentaID;
        
        public DeleteCuentaINTEGRACIONRequestBody() {
        }
        
        public DeleteCuentaINTEGRACIONRequestBody(string cuentaID) {
            this.cuentaID = cuentaID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteCuentaINTEGRACIONResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteCuentaINTEGRACIONResponse", Namespace="http://intec.edu.do", Order=0)]
        public WEB.integracionSR.DeleteCuentaINTEGRACIONResponseBody Body;
        
        public DeleteCuentaINTEGRACIONResponse() {
        }
        
        public DeleteCuentaINTEGRACIONResponse(WEB.integracionSR.DeleteCuentaINTEGRACIONResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://intec.edu.do")]
    public partial class DeleteCuentaINTEGRACIONResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string DeleteCuentaINTEGRACIONResult;
        
        public DeleteCuentaINTEGRACIONResponseBody() {
        }
        
        public DeleteCuentaINTEGRACIONResponseBody(string DeleteCuentaINTEGRACIONResult) {
            this.DeleteCuentaINTEGRACIONResult = DeleteCuentaINTEGRACIONResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertFacturaINTEGRACIONRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertFacturaINTEGRACION", Namespace="http://intec.edu.do", Order=0)]
        public WEB.integracionSR.InsertFacturaINTEGRACIONRequestBody Body;
        
        public InsertFacturaINTEGRACIONRequest() {
        }
        
        public InsertFacturaINTEGRACIONRequest(WEB.integracionSR.InsertFacturaINTEGRACIONRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://intec.edu.do")]
    public partial class InsertFacturaINTEGRACIONRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Nombres;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Apellidos;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Producto;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public decimal Total;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string cuentaID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Cedula;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string facturadoPor;
        
        public InsertFacturaINTEGRACIONRequestBody() {
        }
        
        public InsertFacturaINTEGRACIONRequestBody(string Nombres, string Apellidos, string Producto, decimal Total, string cuentaID, string Cedula, string facturadoPor) {
            this.Nombres = Nombres;
            this.Apellidos = Apellidos;
            this.Producto = Producto;
            this.Total = Total;
            this.cuentaID = cuentaID;
            this.Cedula = Cedula;
            this.facturadoPor = facturadoPor;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertFacturaINTEGRACIONResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertFacturaINTEGRACIONResponse", Namespace="http://intec.edu.do", Order=0)]
        public WEB.integracionSR.InsertFacturaINTEGRACIONResponseBody Body;
        
        public InsertFacturaINTEGRACIONResponse() {
        }
        
        public InsertFacturaINTEGRACIONResponse(WEB.integracionSR.InsertFacturaINTEGRACIONResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://intec.edu.do")]
    public partial class InsertFacturaINTEGRACIONResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string InsertFacturaINTEGRACIONResult;
        
        public InsertFacturaINTEGRACIONResponseBody() {
        }
        
        public InsertFacturaINTEGRACIONResponseBody(string InsertFacturaINTEGRACIONResult) {
            this.InsertFacturaINTEGRACIONResult = InsertFacturaINTEGRACIONResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface integracionSWSoapChannel : WEB.integracionSR.integracionSWSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class integracionSWSoapClient : System.ServiceModel.ClientBase<WEB.integracionSR.integracionSWSoap>, WEB.integracionSR.integracionSWSoap {
        
        public integracionSWSoapClient() {
        }
        
        public integracionSWSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public integracionSWSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public integracionSWSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public integracionSWSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WEB.integracionSR.InsertarProductoINTEGRACIONResponse WEB.integracionSR.integracionSWSoap.InsertarProductoINTEGRACION(WEB.integracionSR.InsertarProductoINTEGRACIONRequest request) {
            return base.Channel.InsertarProductoINTEGRACION(request);
        }
        
        public string InsertarProductoINTEGRACION(string codigo, string marca, decimal precio, int cantidad, string tipo, string nombre, int peso, string imagen, string descripcion) {
            WEB.integracionSR.InsertarProductoINTEGRACIONRequest inValue = new WEB.integracionSR.InsertarProductoINTEGRACIONRequest();
            inValue.Body = new WEB.integracionSR.InsertarProductoINTEGRACIONRequestBody();
            inValue.Body.codigo = codigo;
            inValue.Body.marca = marca;
            inValue.Body.precio = precio;
            inValue.Body.cantidad = cantidad;
            inValue.Body.tipo = tipo;
            inValue.Body.nombre = nombre;
            inValue.Body.peso = peso;
            inValue.Body.imagen = imagen;
            inValue.Body.descripcion = descripcion;
            WEB.integracionSR.InsertarProductoINTEGRACIONResponse retVal = ((WEB.integracionSR.integracionSWSoap)(this)).InsertarProductoINTEGRACION(inValue);
            return retVal.Body.InsertarProductoINTEGRACIONResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WEB.integracionSR.InsertarProductoINTEGRACIONResponse> WEB.integracionSR.integracionSWSoap.InsertarProductoINTEGRACIONAsync(WEB.integracionSR.InsertarProductoINTEGRACIONRequest request) {
            return base.Channel.InsertarProductoINTEGRACIONAsync(request);
        }
        
        public System.Threading.Tasks.Task<WEB.integracionSR.InsertarProductoINTEGRACIONResponse> InsertarProductoINTEGRACIONAsync(string codigo, string marca, decimal precio, int cantidad, string tipo, string nombre, int peso, string imagen, string descripcion) {
            WEB.integracionSR.InsertarProductoINTEGRACIONRequest inValue = new WEB.integracionSR.InsertarProductoINTEGRACIONRequest();
            inValue.Body = new WEB.integracionSR.InsertarProductoINTEGRACIONRequestBody();
            inValue.Body.codigo = codigo;
            inValue.Body.marca = marca;
            inValue.Body.precio = precio;
            inValue.Body.cantidad = cantidad;
            inValue.Body.tipo = tipo;
            inValue.Body.nombre = nombre;
            inValue.Body.peso = peso;
            inValue.Body.imagen = imagen;
            inValue.Body.descripcion = descripcion;
            return ((WEB.integracionSR.integracionSWSoap)(this)).InsertarProductoINTEGRACIONAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WEB.integracionSR.DeleteProductoINTEGRACIONResponse WEB.integracionSR.integracionSWSoap.DeleteProductoINTEGRACION(WEB.integracionSR.DeleteProductoINTEGRACIONRequest request) {
            return base.Channel.DeleteProductoINTEGRACION(request);
        }
        
        public string DeleteProductoINTEGRACION(string codigo) {
            WEB.integracionSR.DeleteProductoINTEGRACIONRequest inValue = new WEB.integracionSR.DeleteProductoINTEGRACIONRequest();
            inValue.Body = new WEB.integracionSR.DeleteProductoINTEGRACIONRequestBody();
            inValue.Body.codigo = codigo;
            WEB.integracionSR.DeleteProductoINTEGRACIONResponse retVal = ((WEB.integracionSR.integracionSWSoap)(this)).DeleteProductoINTEGRACION(inValue);
            return retVal.Body.DeleteProductoINTEGRACIONResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WEB.integracionSR.DeleteProductoINTEGRACIONResponse> WEB.integracionSR.integracionSWSoap.DeleteProductoINTEGRACIONAsync(WEB.integracionSR.DeleteProductoINTEGRACIONRequest request) {
            return base.Channel.DeleteProductoINTEGRACIONAsync(request);
        }
        
        public System.Threading.Tasks.Task<WEB.integracionSR.DeleteProductoINTEGRACIONResponse> DeleteProductoINTEGRACIONAsync(string codigo) {
            WEB.integracionSR.DeleteProductoINTEGRACIONRequest inValue = new WEB.integracionSR.DeleteProductoINTEGRACIONRequest();
            inValue.Body = new WEB.integracionSR.DeleteProductoINTEGRACIONRequestBody();
            inValue.Body.codigo = codigo;
            return ((WEB.integracionSR.integracionSWSoap)(this)).DeleteProductoINTEGRACIONAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WEB.integracionSR.UpdateProductoINTEGRACIONResponse WEB.integracionSR.integracionSWSoap.UpdateProductoINTEGRACION(WEB.integracionSR.UpdateProductoINTEGRACIONRequest request) {
            return base.Channel.UpdateProductoINTEGRACION(request);
        }
        
        public string UpdateProductoINTEGRACION(string codigo, string usuarioCedula) {
            WEB.integracionSR.UpdateProductoINTEGRACIONRequest inValue = new WEB.integracionSR.UpdateProductoINTEGRACIONRequest();
            inValue.Body = new WEB.integracionSR.UpdateProductoINTEGRACIONRequestBody();
            inValue.Body.codigo = codigo;
            inValue.Body.usuarioCedula = usuarioCedula;
            WEB.integracionSR.UpdateProductoINTEGRACIONResponse retVal = ((WEB.integracionSR.integracionSWSoap)(this)).UpdateProductoINTEGRACION(inValue);
            return retVal.Body.UpdateProductoINTEGRACIONResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WEB.integracionSR.UpdateProductoINTEGRACIONResponse> WEB.integracionSR.integracionSWSoap.UpdateProductoINTEGRACIONAsync(WEB.integracionSR.UpdateProductoINTEGRACIONRequest request) {
            return base.Channel.UpdateProductoINTEGRACIONAsync(request);
        }
        
        public System.Threading.Tasks.Task<WEB.integracionSR.UpdateProductoINTEGRACIONResponse> UpdateProductoINTEGRACIONAsync(string codigo, string usuarioCedula) {
            WEB.integracionSR.UpdateProductoINTEGRACIONRequest inValue = new WEB.integracionSR.UpdateProductoINTEGRACIONRequest();
            inValue.Body = new WEB.integracionSR.UpdateProductoINTEGRACIONRequestBody();
            inValue.Body.codigo = codigo;
            inValue.Body.usuarioCedula = usuarioCedula;
            return ((WEB.integracionSR.integracionSWSoap)(this)).UpdateProductoINTEGRACIONAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WEB.integracionSR.InsertClienteINTEGRACIONResponse WEB.integracionSR.integracionSWSoap.InsertClienteINTEGRACION(WEB.integracionSR.InsertClienteINTEGRACIONRequest request) {
            return base.Channel.InsertClienteINTEGRACION(request);
        }
        
        public string InsertClienteINTEGRACION(string Nombres, string Apellidos, string Cedula, string Telefono, System.DateTime fechaNacimiento, string Email, string Password, string Sexo) {
            WEB.integracionSR.InsertClienteINTEGRACIONRequest inValue = new WEB.integracionSR.InsertClienteINTEGRACIONRequest();
            inValue.Body = new WEB.integracionSR.InsertClienteINTEGRACIONRequestBody();
            inValue.Body.Nombres = Nombres;
            inValue.Body.Apellidos = Apellidos;
            inValue.Body.Cedula = Cedula;
            inValue.Body.Telefono = Telefono;
            inValue.Body.fechaNacimiento = fechaNacimiento;
            inValue.Body.Email = Email;
            inValue.Body.Password = Password;
            inValue.Body.Sexo = Sexo;
            WEB.integracionSR.InsertClienteINTEGRACIONResponse retVal = ((WEB.integracionSR.integracionSWSoap)(this)).InsertClienteINTEGRACION(inValue);
            return retVal.Body.InsertClienteINTEGRACIONResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WEB.integracionSR.InsertClienteINTEGRACIONResponse> WEB.integracionSR.integracionSWSoap.InsertClienteINTEGRACIONAsync(WEB.integracionSR.InsertClienteINTEGRACIONRequest request) {
            return base.Channel.InsertClienteINTEGRACIONAsync(request);
        }
        
        public System.Threading.Tasks.Task<WEB.integracionSR.InsertClienteINTEGRACIONResponse> InsertClienteINTEGRACIONAsync(string Nombres, string Apellidos, string Cedula, string Telefono, System.DateTime fechaNacimiento, string Email, string Password, string Sexo) {
            WEB.integracionSR.InsertClienteINTEGRACIONRequest inValue = new WEB.integracionSR.InsertClienteINTEGRACIONRequest();
            inValue.Body = new WEB.integracionSR.InsertClienteINTEGRACIONRequestBody();
            inValue.Body.Nombres = Nombres;
            inValue.Body.Apellidos = Apellidos;
            inValue.Body.Cedula = Cedula;
            inValue.Body.Telefono = Telefono;
            inValue.Body.fechaNacimiento = fechaNacimiento;
            inValue.Body.Email = Email;
            inValue.Body.Password = Password;
            inValue.Body.Sexo = Sexo;
            return ((WEB.integracionSR.integracionSWSoap)(this)).InsertClienteINTEGRACIONAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WEB.integracionSR.DeleteClienteINTEGRACIONResponse WEB.integracionSR.integracionSWSoap.DeleteClienteINTEGRACION(WEB.integracionSR.DeleteClienteINTEGRACIONRequest request) {
            return base.Channel.DeleteClienteINTEGRACION(request);
        }
        
        public string DeleteClienteINTEGRACION(string Cedula) {
            WEB.integracionSR.DeleteClienteINTEGRACIONRequest inValue = new WEB.integracionSR.DeleteClienteINTEGRACIONRequest();
            inValue.Body = new WEB.integracionSR.DeleteClienteINTEGRACIONRequestBody();
            inValue.Body.Cedula = Cedula;
            WEB.integracionSR.DeleteClienteINTEGRACIONResponse retVal = ((WEB.integracionSR.integracionSWSoap)(this)).DeleteClienteINTEGRACION(inValue);
            return retVal.Body.DeleteClienteINTEGRACIONResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WEB.integracionSR.DeleteClienteINTEGRACIONResponse> WEB.integracionSR.integracionSWSoap.DeleteClienteINTEGRACIONAsync(WEB.integracionSR.DeleteClienteINTEGRACIONRequest request) {
            return base.Channel.DeleteClienteINTEGRACIONAsync(request);
        }
        
        public System.Threading.Tasks.Task<WEB.integracionSR.DeleteClienteINTEGRACIONResponse> DeleteClienteINTEGRACIONAsync(string Cedula) {
            WEB.integracionSR.DeleteClienteINTEGRACIONRequest inValue = new WEB.integracionSR.DeleteClienteINTEGRACIONRequest();
            inValue.Body = new WEB.integracionSR.DeleteClienteINTEGRACIONRequestBody();
            inValue.Body.Cedula = Cedula;
            return ((WEB.integracionSR.integracionSWSoap)(this)).DeleteClienteINTEGRACIONAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WEB.integracionSR.UpdateClienteINTEGRACIONResponse WEB.integracionSR.integracionSWSoap.UpdateClienteINTEGRACION(WEB.integracionSR.UpdateClienteINTEGRACIONRequest request) {
            return base.Channel.UpdateClienteINTEGRACION(request);
        }
        
        public string UpdateClienteINTEGRACION(decimal totalGastado, string Cedula) {
            WEB.integracionSR.UpdateClienteINTEGRACIONRequest inValue = new WEB.integracionSR.UpdateClienteINTEGRACIONRequest();
            inValue.Body = new WEB.integracionSR.UpdateClienteINTEGRACIONRequestBody();
            inValue.Body.totalGastado = totalGastado;
            inValue.Body.Cedula = Cedula;
            WEB.integracionSR.UpdateClienteINTEGRACIONResponse retVal = ((WEB.integracionSR.integracionSWSoap)(this)).UpdateClienteINTEGRACION(inValue);
            return retVal.Body.UpdateClienteINTEGRACIONResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WEB.integracionSR.UpdateClienteINTEGRACIONResponse> WEB.integracionSR.integracionSWSoap.UpdateClienteINTEGRACIONAsync(WEB.integracionSR.UpdateClienteINTEGRACIONRequest request) {
            return base.Channel.UpdateClienteINTEGRACIONAsync(request);
        }
        
        public System.Threading.Tasks.Task<WEB.integracionSR.UpdateClienteINTEGRACIONResponse> UpdateClienteINTEGRACIONAsync(decimal totalGastado, string Cedula) {
            WEB.integracionSR.UpdateClienteINTEGRACIONRequest inValue = new WEB.integracionSR.UpdateClienteINTEGRACIONRequest();
            inValue.Body = new WEB.integracionSR.UpdateClienteINTEGRACIONRequestBody();
            inValue.Body.totalGastado = totalGastado;
            inValue.Body.Cedula = Cedula;
            return ((WEB.integracionSR.integracionSWSoap)(this)).UpdateClienteINTEGRACIONAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WEB.integracionSR.InsertEmpleadoINTEGRACIONResponse WEB.integracionSR.integracionSWSoap.InsertEmpleadoINTEGRACION(WEB.integracionSR.InsertEmpleadoINTEGRACIONRequest request) {
            return base.Channel.InsertEmpleadoINTEGRACION(request);
        }
        
        public string InsertEmpleadoINTEGRACION(string Nombres, string Apellidos, string Cedula, string Telefono, string rol, string Email, string Password, string Sexo) {
            WEB.integracionSR.InsertEmpleadoINTEGRACIONRequest inValue = new WEB.integracionSR.InsertEmpleadoINTEGRACIONRequest();
            inValue.Body = new WEB.integracionSR.InsertEmpleadoINTEGRACIONRequestBody();
            inValue.Body.Nombres = Nombres;
            inValue.Body.Apellidos = Apellidos;
            inValue.Body.Cedula = Cedula;
            inValue.Body.Telefono = Telefono;
            inValue.Body.rol = rol;
            inValue.Body.Email = Email;
            inValue.Body.Password = Password;
            inValue.Body.Sexo = Sexo;
            WEB.integracionSR.InsertEmpleadoINTEGRACIONResponse retVal = ((WEB.integracionSR.integracionSWSoap)(this)).InsertEmpleadoINTEGRACION(inValue);
            return retVal.Body.InsertEmpleadoINTEGRACIONResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WEB.integracionSR.InsertEmpleadoINTEGRACIONResponse> WEB.integracionSR.integracionSWSoap.InsertEmpleadoINTEGRACIONAsync(WEB.integracionSR.InsertEmpleadoINTEGRACIONRequest request) {
            return base.Channel.InsertEmpleadoINTEGRACIONAsync(request);
        }
        
        public System.Threading.Tasks.Task<WEB.integracionSR.InsertEmpleadoINTEGRACIONResponse> InsertEmpleadoINTEGRACIONAsync(string Nombres, string Apellidos, string Cedula, string Telefono, string rol, string Email, string Password, string Sexo) {
            WEB.integracionSR.InsertEmpleadoINTEGRACIONRequest inValue = new WEB.integracionSR.InsertEmpleadoINTEGRACIONRequest();
            inValue.Body = new WEB.integracionSR.InsertEmpleadoINTEGRACIONRequestBody();
            inValue.Body.Nombres = Nombres;
            inValue.Body.Apellidos = Apellidos;
            inValue.Body.Cedula = Cedula;
            inValue.Body.Telefono = Telefono;
            inValue.Body.rol = rol;
            inValue.Body.Email = Email;
            inValue.Body.Password = Password;
            inValue.Body.Sexo = Sexo;
            return ((WEB.integracionSR.integracionSWSoap)(this)).InsertEmpleadoINTEGRACIONAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WEB.integracionSR.DeleteEmpleadoINTEGRACIONResponse WEB.integracionSR.integracionSWSoap.DeleteEmpleadoINTEGRACION(WEB.integracionSR.DeleteEmpleadoINTEGRACIONRequest request) {
            return base.Channel.DeleteEmpleadoINTEGRACION(request);
        }
        
        public string DeleteEmpleadoINTEGRACION(string Cedula) {
            WEB.integracionSR.DeleteEmpleadoINTEGRACIONRequest inValue = new WEB.integracionSR.DeleteEmpleadoINTEGRACIONRequest();
            inValue.Body = new WEB.integracionSR.DeleteEmpleadoINTEGRACIONRequestBody();
            inValue.Body.Cedula = Cedula;
            WEB.integracionSR.DeleteEmpleadoINTEGRACIONResponse retVal = ((WEB.integracionSR.integracionSWSoap)(this)).DeleteEmpleadoINTEGRACION(inValue);
            return retVal.Body.DeleteEmpleadoINTEGRACIONResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WEB.integracionSR.DeleteEmpleadoINTEGRACIONResponse> WEB.integracionSR.integracionSWSoap.DeleteEmpleadoINTEGRACIONAsync(WEB.integracionSR.DeleteEmpleadoINTEGRACIONRequest request) {
            return base.Channel.DeleteEmpleadoINTEGRACIONAsync(request);
        }
        
        public System.Threading.Tasks.Task<WEB.integracionSR.DeleteEmpleadoINTEGRACIONResponse> DeleteEmpleadoINTEGRACIONAsync(string Cedula) {
            WEB.integracionSR.DeleteEmpleadoINTEGRACIONRequest inValue = new WEB.integracionSR.DeleteEmpleadoINTEGRACIONRequest();
            inValue.Body = new WEB.integracionSR.DeleteEmpleadoINTEGRACIONRequestBody();
            inValue.Body.Cedula = Cedula;
            return ((WEB.integracionSR.integracionSWSoap)(this)).DeleteEmpleadoINTEGRACIONAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WEB.integracionSR.UpdateEmpleadoINTEGRACIONResponse WEB.integracionSR.integracionSWSoap.UpdateEmpleadoINTEGRACION(WEB.integracionSR.UpdateEmpleadoINTEGRACIONRequest request) {
            return base.Channel.UpdateEmpleadoINTEGRACION(request);
        }
        
        public string UpdateEmpleadoINTEGRACION(int cuentasCobradas, string Cedula) {
            WEB.integracionSR.UpdateEmpleadoINTEGRACIONRequest inValue = new WEB.integracionSR.UpdateEmpleadoINTEGRACIONRequest();
            inValue.Body = new WEB.integracionSR.UpdateEmpleadoINTEGRACIONRequestBody();
            inValue.Body.cuentasCobradas = cuentasCobradas;
            inValue.Body.Cedula = Cedula;
            WEB.integracionSR.UpdateEmpleadoINTEGRACIONResponse retVal = ((WEB.integracionSR.integracionSWSoap)(this)).UpdateEmpleadoINTEGRACION(inValue);
            return retVal.Body.UpdateEmpleadoINTEGRACIONResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WEB.integracionSR.UpdateEmpleadoINTEGRACIONResponse> WEB.integracionSR.integracionSWSoap.UpdateEmpleadoINTEGRACIONAsync(WEB.integracionSR.UpdateEmpleadoINTEGRACIONRequest request) {
            return base.Channel.UpdateEmpleadoINTEGRACIONAsync(request);
        }
        
        public System.Threading.Tasks.Task<WEB.integracionSR.UpdateEmpleadoINTEGRACIONResponse> UpdateEmpleadoINTEGRACIONAsync(int cuentasCobradas, string Cedula) {
            WEB.integracionSR.UpdateEmpleadoINTEGRACIONRequest inValue = new WEB.integracionSR.UpdateEmpleadoINTEGRACIONRequest();
            inValue.Body = new WEB.integracionSR.UpdateEmpleadoINTEGRACIONRequestBody();
            inValue.Body.cuentasCobradas = cuentasCobradas;
            inValue.Body.Cedula = Cedula;
            return ((WEB.integracionSR.integracionSWSoap)(this)).UpdateEmpleadoINTEGRACIONAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WEB.integracionSR.InsertCuentaINTEGRACIONResponse WEB.integracionSR.integracionSWSoap.InsertCuentaINTEGRACION(WEB.integracionSR.InsertCuentaINTEGRACIONRequest request) {
            return base.Channel.InsertCuentaINTEGRACION(request);
        }
        
        public string InsertCuentaINTEGRACION(string Nombres, string Apellidos, string Producto, decimal Total, string cuentaID, string Cedula) {
            WEB.integracionSR.InsertCuentaINTEGRACIONRequest inValue = new WEB.integracionSR.InsertCuentaINTEGRACIONRequest();
            inValue.Body = new WEB.integracionSR.InsertCuentaINTEGRACIONRequestBody();
            inValue.Body.Nombres = Nombres;
            inValue.Body.Apellidos = Apellidos;
            inValue.Body.Producto = Producto;
            inValue.Body.Total = Total;
            inValue.Body.cuentaID = cuentaID;
            inValue.Body.Cedula = Cedula;
            WEB.integracionSR.InsertCuentaINTEGRACIONResponse retVal = ((WEB.integracionSR.integracionSWSoap)(this)).InsertCuentaINTEGRACION(inValue);
            return retVal.Body.InsertCuentaINTEGRACIONResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WEB.integracionSR.InsertCuentaINTEGRACIONResponse> WEB.integracionSR.integracionSWSoap.InsertCuentaINTEGRACIONAsync(WEB.integracionSR.InsertCuentaINTEGRACIONRequest request) {
            return base.Channel.InsertCuentaINTEGRACIONAsync(request);
        }
        
        public System.Threading.Tasks.Task<WEB.integracionSR.InsertCuentaINTEGRACIONResponse> InsertCuentaINTEGRACIONAsync(string Nombres, string Apellidos, string Producto, decimal Total, string cuentaID, string Cedula) {
            WEB.integracionSR.InsertCuentaINTEGRACIONRequest inValue = new WEB.integracionSR.InsertCuentaINTEGRACIONRequest();
            inValue.Body = new WEB.integracionSR.InsertCuentaINTEGRACIONRequestBody();
            inValue.Body.Nombres = Nombres;
            inValue.Body.Apellidos = Apellidos;
            inValue.Body.Producto = Producto;
            inValue.Body.Total = Total;
            inValue.Body.cuentaID = cuentaID;
            inValue.Body.Cedula = Cedula;
            return ((WEB.integracionSR.integracionSWSoap)(this)).InsertCuentaINTEGRACIONAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WEB.integracionSR.DeleteCuentaINTEGRACIONResponse WEB.integracionSR.integracionSWSoap.DeleteCuentaINTEGRACION(WEB.integracionSR.DeleteCuentaINTEGRACIONRequest request) {
            return base.Channel.DeleteCuentaINTEGRACION(request);
        }
        
        public string DeleteCuentaINTEGRACION(string cuentaID) {
            WEB.integracionSR.DeleteCuentaINTEGRACIONRequest inValue = new WEB.integracionSR.DeleteCuentaINTEGRACIONRequest();
            inValue.Body = new WEB.integracionSR.DeleteCuentaINTEGRACIONRequestBody();
            inValue.Body.cuentaID = cuentaID;
            WEB.integracionSR.DeleteCuentaINTEGRACIONResponse retVal = ((WEB.integracionSR.integracionSWSoap)(this)).DeleteCuentaINTEGRACION(inValue);
            return retVal.Body.DeleteCuentaINTEGRACIONResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WEB.integracionSR.DeleteCuentaINTEGRACIONResponse> WEB.integracionSR.integracionSWSoap.DeleteCuentaINTEGRACIONAsync(WEB.integracionSR.DeleteCuentaINTEGRACIONRequest request) {
            return base.Channel.DeleteCuentaINTEGRACIONAsync(request);
        }
        
        public System.Threading.Tasks.Task<WEB.integracionSR.DeleteCuentaINTEGRACIONResponse> DeleteCuentaINTEGRACIONAsync(string cuentaID) {
            WEB.integracionSR.DeleteCuentaINTEGRACIONRequest inValue = new WEB.integracionSR.DeleteCuentaINTEGRACIONRequest();
            inValue.Body = new WEB.integracionSR.DeleteCuentaINTEGRACIONRequestBody();
            inValue.Body.cuentaID = cuentaID;
            return ((WEB.integracionSR.integracionSWSoap)(this)).DeleteCuentaINTEGRACIONAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WEB.integracionSR.InsertFacturaINTEGRACIONResponse WEB.integracionSR.integracionSWSoap.InsertFacturaINTEGRACION(WEB.integracionSR.InsertFacturaINTEGRACIONRequest request) {
            return base.Channel.InsertFacturaINTEGRACION(request);
        }
        
        public string InsertFacturaINTEGRACION(string Nombres, string Apellidos, string Producto, decimal Total, string cuentaID, string Cedula, string facturadoPor) {
            WEB.integracionSR.InsertFacturaINTEGRACIONRequest inValue = new WEB.integracionSR.InsertFacturaINTEGRACIONRequest();
            inValue.Body = new WEB.integracionSR.InsertFacturaINTEGRACIONRequestBody();
            inValue.Body.Nombres = Nombres;
            inValue.Body.Apellidos = Apellidos;
            inValue.Body.Producto = Producto;
            inValue.Body.Total = Total;
            inValue.Body.cuentaID = cuentaID;
            inValue.Body.Cedula = Cedula;
            inValue.Body.facturadoPor = facturadoPor;
            WEB.integracionSR.InsertFacturaINTEGRACIONResponse retVal = ((WEB.integracionSR.integracionSWSoap)(this)).InsertFacturaINTEGRACION(inValue);
            return retVal.Body.InsertFacturaINTEGRACIONResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WEB.integracionSR.InsertFacturaINTEGRACIONResponse> WEB.integracionSR.integracionSWSoap.InsertFacturaINTEGRACIONAsync(WEB.integracionSR.InsertFacturaINTEGRACIONRequest request) {
            return base.Channel.InsertFacturaINTEGRACIONAsync(request);
        }
        
        public System.Threading.Tasks.Task<WEB.integracionSR.InsertFacturaINTEGRACIONResponse> InsertFacturaINTEGRACIONAsync(string Nombres, string Apellidos, string Producto, decimal Total, string cuentaID, string Cedula, string facturadoPor) {
            WEB.integracionSR.InsertFacturaINTEGRACIONRequest inValue = new WEB.integracionSR.InsertFacturaINTEGRACIONRequest();
            inValue.Body = new WEB.integracionSR.InsertFacturaINTEGRACIONRequestBody();
            inValue.Body.Nombres = Nombres;
            inValue.Body.Apellidos = Apellidos;
            inValue.Body.Producto = Producto;
            inValue.Body.Total = Total;
            inValue.Body.cuentaID = cuentaID;
            inValue.Body.Cedula = Cedula;
            inValue.Body.facturadoPor = facturadoPor;
            return ((WEB.integracionSR.integracionSWSoap)(this)).InsertFacturaINTEGRACIONAsync(inValue);
        }
    }
}
