//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INTEGRACION.coreSR {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://intec.edu.do", ConfigurationName="coreSR.coreWSSoap")]
    public interface coreWSSoap {
        
        // CODEGEN: Generating message contract since element name codigo from namespace http://intec.edu.do is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://intec.edu.do/InsertarProductoCORE", ReplyAction="*")]
        INTEGRACION.coreSR.InsertarProductoCOREResponse InsertarProductoCORE(INTEGRACION.coreSR.InsertarProductoCORERequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://intec.edu.do/InsertarProductoCORE", ReplyAction="*")]
        System.Threading.Tasks.Task<INTEGRACION.coreSR.InsertarProductoCOREResponse> InsertarProductoCOREAsync(INTEGRACION.coreSR.InsertarProductoCORERequest request);
        
        // CODEGEN: Generating message contract since element name codigo from namespace http://intec.edu.do is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://intec.edu.do/DeleteProductoCORE", ReplyAction="*")]
        INTEGRACION.coreSR.DeleteProductoCOREResponse DeleteProductoCORE(INTEGRACION.coreSR.DeleteProductoCORERequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://intec.edu.do/DeleteProductoCORE", ReplyAction="*")]
        System.Threading.Tasks.Task<INTEGRACION.coreSR.DeleteProductoCOREResponse> DeleteProductoCOREAsync(INTEGRACION.coreSR.DeleteProductoCORERequest request);
        
        // CODEGEN: Generating message contract since element name Cedula from namespace http://intec.edu.do is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://intec.edu.do/DeleteClienteCORE", ReplyAction="*")]
        INTEGRACION.coreSR.DeleteClienteCOREResponse DeleteClienteCORE(INTEGRACION.coreSR.DeleteClienteCORERequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://intec.edu.do/DeleteClienteCORE", ReplyAction="*")]
        System.Threading.Tasks.Task<INTEGRACION.coreSR.DeleteClienteCOREResponse> DeleteClienteCOREAsync(INTEGRACION.coreSR.DeleteClienteCORERequest request);
        
        // CODEGEN: Generating message contract since element name Nombres from namespace http://intec.edu.do is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://intec.edu.do/InsertEmpleadoCORE", ReplyAction="*")]
        INTEGRACION.coreSR.InsertEmpleadoCOREResponse InsertEmpleadoCORE(INTEGRACION.coreSR.InsertEmpleadoCORERequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://intec.edu.do/InsertEmpleadoCORE", ReplyAction="*")]
        System.Threading.Tasks.Task<INTEGRACION.coreSR.InsertEmpleadoCOREResponse> InsertEmpleadoCOREAsync(INTEGRACION.coreSR.InsertEmpleadoCORERequest request);
        
        // CODEGEN: Generating message contract since element name Cedula from namespace http://intec.edu.do is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://intec.edu.do/DeleteEmpleadoCORE", ReplyAction="*")]
        INTEGRACION.coreSR.DeleteEmpleadoCOREResponse DeleteEmpleadoCORE(INTEGRACION.coreSR.DeleteEmpleadoCORERequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://intec.edu.do/DeleteEmpleadoCORE", ReplyAction="*")]
        System.Threading.Tasks.Task<INTEGRACION.coreSR.DeleteEmpleadoCOREResponse> DeleteEmpleadoCOREAsync(INTEGRACION.coreSR.DeleteEmpleadoCORERequest request);
        
        // CODEGEN: Generating message contract since element name Cedula from namespace http://intec.edu.do is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://intec.edu.do/UpdateClienteCORE", ReplyAction="*")]
        INTEGRACION.coreSR.UpdateClienteCOREResponse UpdateClienteCORE(INTEGRACION.coreSR.UpdateClienteCORERequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://intec.edu.do/UpdateClienteCORE", ReplyAction="*")]
        System.Threading.Tasks.Task<INTEGRACION.coreSR.UpdateClienteCOREResponse> UpdateClienteCOREAsync(INTEGRACION.coreSR.UpdateClienteCORERequest request);
        
        // CODEGEN: Generating message contract since element name Cedula from namespace http://intec.edu.do is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://intec.edu.do/UpdateEmpleadoCORE", ReplyAction="*")]
        INTEGRACION.coreSR.UpdateEmpleadoCOREResponse UpdateEmpleadoCORE(INTEGRACION.coreSR.UpdateEmpleadoCORERequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://intec.edu.do/UpdateEmpleadoCORE", ReplyAction="*")]
        System.Threading.Tasks.Task<INTEGRACION.coreSR.UpdateEmpleadoCOREResponse> UpdateEmpleadoCOREAsync(INTEGRACION.coreSR.UpdateEmpleadoCORERequest request);
        
        // CODEGEN: Generating message contract since element name codigo from namespace http://intec.edu.do is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://intec.edu.do/UpdateProductoCORE", ReplyAction="*")]
        INTEGRACION.coreSR.UpdateProductoCOREResponse UpdateProductoCORE(INTEGRACION.coreSR.UpdateProductoCORERequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://intec.edu.do/UpdateProductoCORE", ReplyAction="*")]
        System.Threading.Tasks.Task<INTEGRACION.coreSR.UpdateProductoCOREResponse> UpdateProductoCOREAsync(INTEGRACION.coreSR.UpdateProductoCORERequest request);
        
        // CODEGEN: Generating message contract since element name Nombres from namespace http://intec.edu.do is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://intec.edu.do/InsertClienteCORE", ReplyAction="*")]
        INTEGRACION.coreSR.InsertClienteCOREResponse InsertClienteCORE(INTEGRACION.coreSR.InsertClienteCORERequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://intec.edu.do/InsertClienteCORE", ReplyAction="*")]
        System.Threading.Tasks.Task<INTEGRACION.coreSR.InsertClienteCOREResponse> InsertClienteCOREAsync(INTEGRACION.coreSR.InsertClienteCORERequest request);
        
        // CODEGEN: Generating message contract since element name Nombres from namespace http://intec.edu.do is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://intec.edu.do/InsertCuentaCORE", ReplyAction="*")]
        INTEGRACION.coreSR.InsertCuentaCOREResponse InsertCuentaCORE(INTEGRACION.coreSR.InsertCuentaCORERequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://intec.edu.do/InsertCuentaCORE", ReplyAction="*")]
        System.Threading.Tasks.Task<INTEGRACION.coreSR.InsertCuentaCOREResponse> InsertCuentaCOREAsync(INTEGRACION.coreSR.InsertCuentaCORERequest request);
        
        // CODEGEN: Generating message contract since element name cuentaID from namespace http://intec.edu.do is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://intec.edu.do/DeleteCuentaCORE", ReplyAction="*")]
        INTEGRACION.coreSR.DeleteCuentaCOREResponse DeleteCuentaCORE(INTEGRACION.coreSR.DeleteCuentaCORERequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://intec.edu.do/DeleteCuentaCORE", ReplyAction="*")]
        System.Threading.Tasks.Task<INTEGRACION.coreSR.DeleteCuentaCOREResponse> DeleteCuentaCOREAsync(INTEGRACION.coreSR.DeleteCuentaCORERequest request);
        
        // CODEGEN: Generating message contract since element name Nombres from namespace http://intec.edu.do is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://intec.edu.do/InsertFacturaCORE", ReplyAction="*")]
        INTEGRACION.coreSR.InsertFacturaCOREResponse InsertFacturaCORE(INTEGRACION.coreSR.InsertFacturaCORERequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://intec.edu.do/InsertFacturaCORE", ReplyAction="*")]
        System.Threading.Tasks.Task<INTEGRACION.coreSR.InsertFacturaCOREResponse> InsertFacturaCOREAsync(INTEGRACION.coreSR.InsertFacturaCORERequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertarProductoCORERequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertarProductoCORE", Namespace="http://intec.edu.do", Order=0)]
        public INTEGRACION.coreSR.InsertarProductoCORERequestBody Body;
        
        public InsertarProductoCORERequest() {
        }
        
        public InsertarProductoCORERequest(INTEGRACION.coreSR.InsertarProductoCORERequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://intec.edu.do")]
    public partial class InsertarProductoCORERequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string codigo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string marca;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public decimal precio;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int cantidad;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string tipo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string nombre;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public int peso;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string imagen;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string descripcion;
        
        public InsertarProductoCORERequestBody() {
        }
        
        public InsertarProductoCORERequestBody(string codigo, string marca, decimal precio, int cantidad, string tipo, string nombre, int peso, string imagen, string descripcion) {
            this.codigo = codigo;
            this.marca = marca;
            this.precio = precio;
            this.cantidad = cantidad;
            this.tipo = tipo;
            this.nombre = nombre;
            this.peso = peso;
            this.imagen = imagen;
            this.descripcion = descripcion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertarProductoCOREResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertarProductoCOREResponse", Namespace="http://intec.edu.do", Order=0)]
        public INTEGRACION.coreSR.InsertarProductoCOREResponseBody Body;
        
        public InsertarProductoCOREResponse() {
        }
        
        public InsertarProductoCOREResponse(INTEGRACION.coreSR.InsertarProductoCOREResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://intec.edu.do")]
    public partial class InsertarProductoCOREResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string InsertarProductoCOREResult;
        
        public InsertarProductoCOREResponseBody() {
        }
        
        public InsertarProductoCOREResponseBody(string InsertarProductoCOREResult) {
            this.InsertarProductoCOREResult = InsertarProductoCOREResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteProductoCORERequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteProductoCORE", Namespace="http://intec.edu.do", Order=0)]
        public INTEGRACION.coreSR.DeleteProductoCORERequestBody Body;
        
        public DeleteProductoCORERequest() {
        }
        
        public DeleteProductoCORERequest(INTEGRACION.coreSR.DeleteProductoCORERequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://intec.edu.do")]
    public partial class DeleteProductoCORERequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string codigo;
        
        public DeleteProductoCORERequestBody() {
        }
        
        public DeleteProductoCORERequestBody(string codigo) {
            this.codigo = codigo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteProductoCOREResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteProductoCOREResponse", Namespace="http://intec.edu.do", Order=0)]
        public INTEGRACION.coreSR.DeleteProductoCOREResponseBody Body;
        
        public DeleteProductoCOREResponse() {
        }
        
        public DeleteProductoCOREResponse(INTEGRACION.coreSR.DeleteProductoCOREResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://intec.edu.do")]
    public partial class DeleteProductoCOREResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string DeleteProductoCOREResult;
        
        public DeleteProductoCOREResponseBody() {
        }
        
        public DeleteProductoCOREResponseBody(string DeleteProductoCOREResult) {
            this.DeleteProductoCOREResult = DeleteProductoCOREResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteClienteCORERequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteClienteCORE", Namespace="http://intec.edu.do", Order=0)]
        public INTEGRACION.coreSR.DeleteClienteCORERequestBody Body;
        
        public DeleteClienteCORERequest() {
        }
        
        public DeleteClienteCORERequest(INTEGRACION.coreSR.DeleteClienteCORERequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://intec.edu.do")]
    public partial class DeleteClienteCORERequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Cedula;
        
        public DeleteClienteCORERequestBody() {
        }
        
        public DeleteClienteCORERequestBody(string Cedula) {
            this.Cedula = Cedula;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteClienteCOREResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteClienteCOREResponse", Namespace="http://intec.edu.do", Order=0)]
        public INTEGRACION.coreSR.DeleteClienteCOREResponseBody Body;
        
        public DeleteClienteCOREResponse() {
        }
        
        public DeleteClienteCOREResponse(INTEGRACION.coreSR.DeleteClienteCOREResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://intec.edu.do")]
    public partial class DeleteClienteCOREResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string DeleteClienteCOREResult;
        
        public DeleteClienteCOREResponseBody() {
        }
        
        public DeleteClienteCOREResponseBody(string DeleteClienteCOREResult) {
            this.DeleteClienteCOREResult = DeleteClienteCOREResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertEmpleadoCORERequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertEmpleadoCORE", Namespace="http://intec.edu.do", Order=0)]
        public INTEGRACION.coreSR.InsertEmpleadoCORERequestBody Body;
        
        public InsertEmpleadoCORERequest() {
        }
        
        public InsertEmpleadoCORERequest(INTEGRACION.coreSR.InsertEmpleadoCORERequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://intec.edu.do")]
    public partial class InsertEmpleadoCORERequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Nombres;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Apellidos;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Cedula;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Telefono;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string rol;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Email;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string Password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string Sexo;
        
        public InsertEmpleadoCORERequestBody() {
        }
        
        public InsertEmpleadoCORERequestBody(string Nombres, string Apellidos, string Cedula, string Telefono, string rol, string Email, string Password, string Sexo) {
            this.Nombres = Nombres;
            this.Apellidos = Apellidos;
            this.Cedula = Cedula;
            this.Telefono = Telefono;
            this.rol = rol;
            this.Email = Email;
            this.Password = Password;
            this.Sexo = Sexo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertEmpleadoCOREResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertEmpleadoCOREResponse", Namespace="http://intec.edu.do", Order=0)]
        public INTEGRACION.coreSR.InsertEmpleadoCOREResponseBody Body;
        
        public InsertEmpleadoCOREResponse() {
        }
        
        public InsertEmpleadoCOREResponse(INTEGRACION.coreSR.InsertEmpleadoCOREResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://intec.edu.do")]
    public partial class InsertEmpleadoCOREResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string InsertEmpleadoCOREResult;
        
        public InsertEmpleadoCOREResponseBody() {
        }
        
        public InsertEmpleadoCOREResponseBody(string InsertEmpleadoCOREResult) {
            this.InsertEmpleadoCOREResult = InsertEmpleadoCOREResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteEmpleadoCORERequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteEmpleadoCORE", Namespace="http://intec.edu.do", Order=0)]
        public INTEGRACION.coreSR.DeleteEmpleadoCORERequestBody Body;
        
        public DeleteEmpleadoCORERequest() {
        }
        
        public DeleteEmpleadoCORERequest(INTEGRACION.coreSR.DeleteEmpleadoCORERequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://intec.edu.do")]
    public partial class DeleteEmpleadoCORERequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Cedula;
        
        public DeleteEmpleadoCORERequestBody() {
        }
        
        public DeleteEmpleadoCORERequestBody(string Cedula) {
            this.Cedula = Cedula;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteEmpleadoCOREResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteEmpleadoCOREResponse", Namespace="http://intec.edu.do", Order=0)]
        public INTEGRACION.coreSR.DeleteEmpleadoCOREResponseBody Body;
        
        public DeleteEmpleadoCOREResponse() {
        }
        
        public DeleteEmpleadoCOREResponse(INTEGRACION.coreSR.DeleteEmpleadoCOREResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://intec.edu.do")]
    public partial class DeleteEmpleadoCOREResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string DeleteEmpleadoCOREResult;
        
        public DeleteEmpleadoCOREResponseBody() {
        }
        
        public DeleteEmpleadoCOREResponseBody(string DeleteEmpleadoCOREResult) {
            this.DeleteEmpleadoCOREResult = DeleteEmpleadoCOREResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateClienteCORERequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateClienteCORE", Namespace="http://intec.edu.do", Order=0)]
        public INTEGRACION.coreSR.UpdateClienteCORERequestBody Body;
        
        public UpdateClienteCORERequest() {
        }
        
        public UpdateClienteCORERequest(INTEGRACION.coreSR.UpdateClienteCORERequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://intec.edu.do")]
    public partial class UpdateClienteCORERequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public decimal totalGastado;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Cedula;
        
        public UpdateClienteCORERequestBody() {
        }
        
        public UpdateClienteCORERequestBody(decimal totalGastado, string Cedula) {
            this.totalGastado = totalGastado;
            this.Cedula = Cedula;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateClienteCOREResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateClienteCOREResponse", Namespace="http://intec.edu.do", Order=0)]
        public INTEGRACION.coreSR.UpdateClienteCOREResponseBody Body;
        
        public UpdateClienteCOREResponse() {
        }
        
        public UpdateClienteCOREResponse(INTEGRACION.coreSR.UpdateClienteCOREResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://intec.edu.do")]
    public partial class UpdateClienteCOREResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UpdateClienteCOREResult;
        
        public UpdateClienteCOREResponseBody() {
        }
        
        public UpdateClienteCOREResponseBody(string UpdateClienteCOREResult) {
            this.UpdateClienteCOREResult = UpdateClienteCOREResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateEmpleadoCORERequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateEmpleadoCORE", Namespace="http://intec.edu.do", Order=0)]
        public INTEGRACION.coreSR.UpdateEmpleadoCORERequestBody Body;
        
        public UpdateEmpleadoCORERequest() {
        }
        
        public UpdateEmpleadoCORERequest(INTEGRACION.coreSR.UpdateEmpleadoCORERequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://intec.edu.do")]
    public partial class UpdateEmpleadoCORERequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int cuentasCobradas;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Cedula;
        
        public UpdateEmpleadoCORERequestBody() {
        }
        
        public UpdateEmpleadoCORERequestBody(int cuentasCobradas, string Cedula) {
            this.cuentasCobradas = cuentasCobradas;
            this.Cedula = Cedula;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateEmpleadoCOREResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateEmpleadoCOREResponse", Namespace="http://intec.edu.do", Order=0)]
        public INTEGRACION.coreSR.UpdateEmpleadoCOREResponseBody Body;
        
        public UpdateEmpleadoCOREResponse() {
        }
        
        public UpdateEmpleadoCOREResponse(INTEGRACION.coreSR.UpdateEmpleadoCOREResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://intec.edu.do")]
    public partial class UpdateEmpleadoCOREResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UpdateEmpleadoCOREResult;
        
        public UpdateEmpleadoCOREResponseBody() {
        }
        
        public UpdateEmpleadoCOREResponseBody(string UpdateEmpleadoCOREResult) {
            this.UpdateEmpleadoCOREResult = UpdateEmpleadoCOREResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateProductoCORERequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateProductoCORE", Namespace="http://intec.edu.do", Order=0)]
        public INTEGRACION.coreSR.UpdateProductoCORERequestBody Body;
        
        public UpdateProductoCORERequest() {
        }
        
        public UpdateProductoCORERequest(INTEGRACION.coreSR.UpdateProductoCORERequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://intec.edu.do")]
    public partial class UpdateProductoCORERequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string codigo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string usuarioCedula;
        
        public UpdateProductoCORERequestBody() {
        }
        
        public UpdateProductoCORERequestBody(string codigo, string usuarioCedula) {
            this.codigo = codigo;
            this.usuarioCedula = usuarioCedula;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateProductoCOREResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateProductoCOREResponse", Namespace="http://intec.edu.do", Order=0)]
        public INTEGRACION.coreSR.UpdateProductoCOREResponseBody Body;
        
        public UpdateProductoCOREResponse() {
        }
        
        public UpdateProductoCOREResponse(INTEGRACION.coreSR.UpdateProductoCOREResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://intec.edu.do")]
    public partial class UpdateProductoCOREResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UpdateProductoCOREResult;
        
        public UpdateProductoCOREResponseBody() {
        }
        
        public UpdateProductoCOREResponseBody(string UpdateProductoCOREResult) {
            this.UpdateProductoCOREResult = UpdateProductoCOREResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertClienteCORERequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertClienteCORE", Namespace="http://intec.edu.do", Order=0)]
        public INTEGRACION.coreSR.InsertClienteCORERequestBody Body;
        
        public InsertClienteCORERequest() {
        }
        
        public InsertClienteCORERequest(INTEGRACION.coreSR.InsertClienteCORERequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://intec.edu.do")]
    public partial class InsertClienteCORERequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Nombres;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Apellidos;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Cedula;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Telefono;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public System.DateTime fechaNacimiento;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Email;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string Password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string Sexo;
        
        public InsertClienteCORERequestBody() {
        }
        
        public InsertClienteCORERequestBody(string Nombres, string Apellidos, string Cedula, string Telefono, System.DateTime fechaNacimiento, string Email, string Password, string Sexo) {
            this.Nombres = Nombres;
            this.Apellidos = Apellidos;
            this.Cedula = Cedula;
            this.Telefono = Telefono;
            this.fechaNacimiento = fechaNacimiento;
            this.Email = Email;
            this.Password = Password;
            this.Sexo = Sexo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertClienteCOREResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertClienteCOREResponse", Namespace="http://intec.edu.do", Order=0)]
        public INTEGRACION.coreSR.InsertClienteCOREResponseBody Body;
        
        public InsertClienteCOREResponse() {
        }
        
        public InsertClienteCOREResponse(INTEGRACION.coreSR.InsertClienteCOREResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://intec.edu.do")]
    public partial class InsertClienteCOREResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string InsertClienteCOREResult;
        
        public InsertClienteCOREResponseBody() {
        }
        
        public InsertClienteCOREResponseBody(string InsertClienteCOREResult) {
            this.InsertClienteCOREResult = InsertClienteCOREResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertCuentaCORERequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertCuentaCORE", Namespace="http://intec.edu.do", Order=0)]
        public INTEGRACION.coreSR.InsertCuentaCORERequestBody Body;
        
        public InsertCuentaCORERequest() {
        }
        
        public InsertCuentaCORERequest(INTEGRACION.coreSR.InsertCuentaCORERequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://intec.edu.do")]
    public partial class InsertCuentaCORERequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Nombres;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Apellidos;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Producto;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public decimal Total;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string cuentaID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Cedula;
        
        public InsertCuentaCORERequestBody() {
        }
        
        public InsertCuentaCORERequestBody(string Nombres, string Apellidos, string Producto, decimal Total, string cuentaID, string Cedula) {
            this.Nombres = Nombres;
            this.Apellidos = Apellidos;
            this.Producto = Producto;
            this.Total = Total;
            this.cuentaID = cuentaID;
            this.Cedula = Cedula;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertCuentaCOREResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertCuentaCOREResponse", Namespace="http://intec.edu.do", Order=0)]
        public INTEGRACION.coreSR.InsertCuentaCOREResponseBody Body;
        
        public InsertCuentaCOREResponse() {
        }
        
        public InsertCuentaCOREResponse(INTEGRACION.coreSR.InsertCuentaCOREResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://intec.edu.do")]
    public partial class InsertCuentaCOREResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string InsertCuentaCOREResult;
        
        public InsertCuentaCOREResponseBody() {
        }
        
        public InsertCuentaCOREResponseBody(string InsertCuentaCOREResult) {
            this.InsertCuentaCOREResult = InsertCuentaCOREResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteCuentaCORERequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteCuentaCORE", Namespace="http://intec.edu.do", Order=0)]
        public INTEGRACION.coreSR.DeleteCuentaCORERequestBody Body;
        
        public DeleteCuentaCORERequest() {
        }
        
        public DeleteCuentaCORERequest(INTEGRACION.coreSR.DeleteCuentaCORERequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://intec.edu.do")]
    public partial class DeleteCuentaCORERequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string cuentaID;
        
        public DeleteCuentaCORERequestBody() {
        }
        
        public DeleteCuentaCORERequestBody(string cuentaID) {
            this.cuentaID = cuentaID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteCuentaCOREResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteCuentaCOREResponse", Namespace="http://intec.edu.do", Order=0)]
        public INTEGRACION.coreSR.DeleteCuentaCOREResponseBody Body;
        
        public DeleteCuentaCOREResponse() {
        }
        
        public DeleteCuentaCOREResponse(INTEGRACION.coreSR.DeleteCuentaCOREResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://intec.edu.do")]
    public partial class DeleteCuentaCOREResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string DeleteCuentaCOREResult;
        
        public DeleteCuentaCOREResponseBody() {
        }
        
        public DeleteCuentaCOREResponseBody(string DeleteCuentaCOREResult) {
            this.DeleteCuentaCOREResult = DeleteCuentaCOREResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertFacturaCORERequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertFacturaCORE", Namespace="http://intec.edu.do", Order=0)]
        public INTEGRACION.coreSR.InsertFacturaCORERequestBody Body;
        
        public InsertFacturaCORERequest() {
        }
        
        public InsertFacturaCORERequest(INTEGRACION.coreSR.InsertFacturaCORERequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://intec.edu.do")]
    public partial class InsertFacturaCORERequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Nombres;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Apellidos;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Producto;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public decimal Total;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string cuentaID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Cedula;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string facturadoPor;
        
        public InsertFacturaCORERequestBody() {
        }
        
        public InsertFacturaCORERequestBody(string Nombres, string Apellidos, string Producto, decimal Total, string cuentaID, string Cedula, string facturadoPor) {
            this.Nombres = Nombres;
            this.Apellidos = Apellidos;
            this.Producto = Producto;
            this.Total = Total;
            this.cuentaID = cuentaID;
            this.Cedula = Cedula;
            this.facturadoPor = facturadoPor;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertFacturaCOREResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertFacturaCOREResponse", Namespace="http://intec.edu.do", Order=0)]
        public INTEGRACION.coreSR.InsertFacturaCOREResponseBody Body;
        
        public InsertFacturaCOREResponse() {
        }
        
        public InsertFacturaCOREResponse(INTEGRACION.coreSR.InsertFacturaCOREResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://intec.edu.do")]
    public partial class InsertFacturaCOREResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string InsertFacturaCOREResult;
        
        public InsertFacturaCOREResponseBody() {
        }
        
        public InsertFacturaCOREResponseBody(string InsertFacturaCOREResult) {
            this.InsertFacturaCOREResult = InsertFacturaCOREResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface coreWSSoapChannel : INTEGRACION.coreSR.coreWSSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class coreWSSoapClient : System.ServiceModel.ClientBase<INTEGRACION.coreSR.coreWSSoap>, INTEGRACION.coreSR.coreWSSoap {
        
        public coreWSSoapClient() {
        }
        
        public coreWSSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public coreWSSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public coreWSSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public coreWSSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        INTEGRACION.coreSR.InsertarProductoCOREResponse INTEGRACION.coreSR.coreWSSoap.InsertarProductoCORE(INTEGRACION.coreSR.InsertarProductoCORERequest request) {
            return base.Channel.InsertarProductoCORE(request);
        }
        
        public string InsertarProductoCORE(string codigo, string marca, decimal precio, int cantidad, string tipo, string nombre, int peso, string imagen, string descripcion) {
            INTEGRACION.coreSR.InsertarProductoCORERequest inValue = new INTEGRACION.coreSR.InsertarProductoCORERequest();
            inValue.Body = new INTEGRACION.coreSR.InsertarProductoCORERequestBody();
            inValue.Body.codigo = codigo;
            inValue.Body.marca = marca;
            inValue.Body.precio = precio;
            inValue.Body.cantidad = cantidad;
            inValue.Body.tipo = tipo;
            inValue.Body.nombre = nombre;
            inValue.Body.peso = peso;
            inValue.Body.imagen = imagen;
            inValue.Body.descripcion = descripcion;
            INTEGRACION.coreSR.InsertarProductoCOREResponse retVal = ((INTEGRACION.coreSR.coreWSSoap)(this)).InsertarProductoCORE(inValue);
            return retVal.Body.InsertarProductoCOREResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<INTEGRACION.coreSR.InsertarProductoCOREResponse> INTEGRACION.coreSR.coreWSSoap.InsertarProductoCOREAsync(INTEGRACION.coreSR.InsertarProductoCORERequest request) {
            return base.Channel.InsertarProductoCOREAsync(request);
        }
        
        public System.Threading.Tasks.Task<INTEGRACION.coreSR.InsertarProductoCOREResponse> InsertarProductoCOREAsync(string codigo, string marca, decimal precio, int cantidad, string tipo, string nombre, int peso, string imagen, string descripcion) {
            INTEGRACION.coreSR.InsertarProductoCORERequest inValue = new INTEGRACION.coreSR.InsertarProductoCORERequest();
            inValue.Body = new INTEGRACION.coreSR.InsertarProductoCORERequestBody();
            inValue.Body.codigo = codigo;
            inValue.Body.marca = marca;
            inValue.Body.precio = precio;
            inValue.Body.cantidad = cantidad;
            inValue.Body.tipo = tipo;
            inValue.Body.nombre = nombre;
            inValue.Body.peso = peso;
            inValue.Body.imagen = imagen;
            inValue.Body.descripcion = descripcion;
            return ((INTEGRACION.coreSR.coreWSSoap)(this)).InsertarProductoCOREAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        INTEGRACION.coreSR.DeleteProductoCOREResponse INTEGRACION.coreSR.coreWSSoap.DeleteProductoCORE(INTEGRACION.coreSR.DeleteProductoCORERequest request) {
            return base.Channel.DeleteProductoCORE(request);
        }
        
        public string DeleteProductoCORE(string codigo) {
            INTEGRACION.coreSR.DeleteProductoCORERequest inValue = new INTEGRACION.coreSR.DeleteProductoCORERequest();
            inValue.Body = new INTEGRACION.coreSR.DeleteProductoCORERequestBody();
            inValue.Body.codigo = codigo;
            INTEGRACION.coreSR.DeleteProductoCOREResponse retVal = ((INTEGRACION.coreSR.coreWSSoap)(this)).DeleteProductoCORE(inValue);
            return retVal.Body.DeleteProductoCOREResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<INTEGRACION.coreSR.DeleteProductoCOREResponse> INTEGRACION.coreSR.coreWSSoap.DeleteProductoCOREAsync(INTEGRACION.coreSR.DeleteProductoCORERequest request) {
            return base.Channel.DeleteProductoCOREAsync(request);
        }
        
        public System.Threading.Tasks.Task<INTEGRACION.coreSR.DeleteProductoCOREResponse> DeleteProductoCOREAsync(string codigo) {
            INTEGRACION.coreSR.DeleteProductoCORERequest inValue = new INTEGRACION.coreSR.DeleteProductoCORERequest();
            inValue.Body = new INTEGRACION.coreSR.DeleteProductoCORERequestBody();
            inValue.Body.codigo = codigo;
            return ((INTEGRACION.coreSR.coreWSSoap)(this)).DeleteProductoCOREAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        INTEGRACION.coreSR.DeleteClienteCOREResponse INTEGRACION.coreSR.coreWSSoap.DeleteClienteCORE(INTEGRACION.coreSR.DeleteClienteCORERequest request) {
            return base.Channel.DeleteClienteCORE(request);
        }
        
        public string DeleteClienteCORE(string Cedula) {
            INTEGRACION.coreSR.DeleteClienteCORERequest inValue = new INTEGRACION.coreSR.DeleteClienteCORERequest();
            inValue.Body = new INTEGRACION.coreSR.DeleteClienteCORERequestBody();
            inValue.Body.Cedula = Cedula;
            INTEGRACION.coreSR.DeleteClienteCOREResponse retVal = ((INTEGRACION.coreSR.coreWSSoap)(this)).DeleteClienteCORE(inValue);
            return retVal.Body.DeleteClienteCOREResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<INTEGRACION.coreSR.DeleteClienteCOREResponse> INTEGRACION.coreSR.coreWSSoap.DeleteClienteCOREAsync(INTEGRACION.coreSR.DeleteClienteCORERequest request) {
            return base.Channel.DeleteClienteCOREAsync(request);
        }
        
        public System.Threading.Tasks.Task<INTEGRACION.coreSR.DeleteClienteCOREResponse> DeleteClienteCOREAsync(string Cedula) {
            INTEGRACION.coreSR.DeleteClienteCORERequest inValue = new INTEGRACION.coreSR.DeleteClienteCORERequest();
            inValue.Body = new INTEGRACION.coreSR.DeleteClienteCORERequestBody();
            inValue.Body.Cedula = Cedula;
            return ((INTEGRACION.coreSR.coreWSSoap)(this)).DeleteClienteCOREAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        INTEGRACION.coreSR.InsertEmpleadoCOREResponse INTEGRACION.coreSR.coreWSSoap.InsertEmpleadoCORE(INTEGRACION.coreSR.InsertEmpleadoCORERequest request) {
            return base.Channel.InsertEmpleadoCORE(request);
        }
        
        public string InsertEmpleadoCORE(string Nombres, string Apellidos, string Cedula, string Telefono, string rol, string Email, string Password, string Sexo) {
            INTEGRACION.coreSR.InsertEmpleadoCORERequest inValue = new INTEGRACION.coreSR.InsertEmpleadoCORERequest();
            inValue.Body = new INTEGRACION.coreSR.InsertEmpleadoCORERequestBody();
            inValue.Body.Nombres = Nombres;
            inValue.Body.Apellidos = Apellidos;
            inValue.Body.Cedula = Cedula;
            inValue.Body.Telefono = Telefono;
            inValue.Body.rol = rol;
            inValue.Body.Email = Email;
            inValue.Body.Password = Password;
            inValue.Body.Sexo = Sexo;
            INTEGRACION.coreSR.InsertEmpleadoCOREResponse retVal = ((INTEGRACION.coreSR.coreWSSoap)(this)).InsertEmpleadoCORE(inValue);
            return retVal.Body.InsertEmpleadoCOREResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<INTEGRACION.coreSR.InsertEmpleadoCOREResponse> INTEGRACION.coreSR.coreWSSoap.InsertEmpleadoCOREAsync(INTEGRACION.coreSR.InsertEmpleadoCORERequest request) {
            return base.Channel.InsertEmpleadoCOREAsync(request);
        }
        
        public System.Threading.Tasks.Task<INTEGRACION.coreSR.InsertEmpleadoCOREResponse> InsertEmpleadoCOREAsync(string Nombres, string Apellidos, string Cedula, string Telefono, string rol, string Email, string Password, string Sexo) {
            INTEGRACION.coreSR.InsertEmpleadoCORERequest inValue = new INTEGRACION.coreSR.InsertEmpleadoCORERequest();
            inValue.Body = new INTEGRACION.coreSR.InsertEmpleadoCORERequestBody();
            inValue.Body.Nombres = Nombres;
            inValue.Body.Apellidos = Apellidos;
            inValue.Body.Cedula = Cedula;
            inValue.Body.Telefono = Telefono;
            inValue.Body.rol = rol;
            inValue.Body.Email = Email;
            inValue.Body.Password = Password;
            inValue.Body.Sexo = Sexo;
            return ((INTEGRACION.coreSR.coreWSSoap)(this)).InsertEmpleadoCOREAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        INTEGRACION.coreSR.DeleteEmpleadoCOREResponse INTEGRACION.coreSR.coreWSSoap.DeleteEmpleadoCORE(INTEGRACION.coreSR.DeleteEmpleadoCORERequest request) {
            return base.Channel.DeleteEmpleadoCORE(request);
        }
        
        public string DeleteEmpleadoCORE(string Cedula) {
            INTEGRACION.coreSR.DeleteEmpleadoCORERequest inValue = new INTEGRACION.coreSR.DeleteEmpleadoCORERequest();
            inValue.Body = new INTEGRACION.coreSR.DeleteEmpleadoCORERequestBody();
            inValue.Body.Cedula = Cedula;
            INTEGRACION.coreSR.DeleteEmpleadoCOREResponse retVal = ((INTEGRACION.coreSR.coreWSSoap)(this)).DeleteEmpleadoCORE(inValue);
            return retVal.Body.DeleteEmpleadoCOREResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<INTEGRACION.coreSR.DeleteEmpleadoCOREResponse> INTEGRACION.coreSR.coreWSSoap.DeleteEmpleadoCOREAsync(INTEGRACION.coreSR.DeleteEmpleadoCORERequest request) {
            return base.Channel.DeleteEmpleadoCOREAsync(request);
        }
        
        public System.Threading.Tasks.Task<INTEGRACION.coreSR.DeleteEmpleadoCOREResponse> DeleteEmpleadoCOREAsync(string Cedula) {
            INTEGRACION.coreSR.DeleteEmpleadoCORERequest inValue = new INTEGRACION.coreSR.DeleteEmpleadoCORERequest();
            inValue.Body = new INTEGRACION.coreSR.DeleteEmpleadoCORERequestBody();
            inValue.Body.Cedula = Cedula;
            return ((INTEGRACION.coreSR.coreWSSoap)(this)).DeleteEmpleadoCOREAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        INTEGRACION.coreSR.UpdateClienteCOREResponse INTEGRACION.coreSR.coreWSSoap.UpdateClienteCORE(INTEGRACION.coreSR.UpdateClienteCORERequest request) {
            return base.Channel.UpdateClienteCORE(request);
        }
        
        public string UpdateClienteCORE(decimal totalGastado, string Cedula) {
            INTEGRACION.coreSR.UpdateClienteCORERequest inValue = new INTEGRACION.coreSR.UpdateClienteCORERequest();
            inValue.Body = new INTEGRACION.coreSR.UpdateClienteCORERequestBody();
            inValue.Body.totalGastado = totalGastado;
            inValue.Body.Cedula = Cedula;
            INTEGRACION.coreSR.UpdateClienteCOREResponse retVal = ((INTEGRACION.coreSR.coreWSSoap)(this)).UpdateClienteCORE(inValue);
            return retVal.Body.UpdateClienteCOREResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<INTEGRACION.coreSR.UpdateClienteCOREResponse> INTEGRACION.coreSR.coreWSSoap.UpdateClienteCOREAsync(INTEGRACION.coreSR.UpdateClienteCORERequest request) {
            return base.Channel.UpdateClienteCOREAsync(request);
        }
        
        public System.Threading.Tasks.Task<INTEGRACION.coreSR.UpdateClienteCOREResponse> UpdateClienteCOREAsync(decimal totalGastado, string Cedula) {
            INTEGRACION.coreSR.UpdateClienteCORERequest inValue = new INTEGRACION.coreSR.UpdateClienteCORERequest();
            inValue.Body = new INTEGRACION.coreSR.UpdateClienteCORERequestBody();
            inValue.Body.totalGastado = totalGastado;
            inValue.Body.Cedula = Cedula;
            return ((INTEGRACION.coreSR.coreWSSoap)(this)).UpdateClienteCOREAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        INTEGRACION.coreSR.UpdateEmpleadoCOREResponse INTEGRACION.coreSR.coreWSSoap.UpdateEmpleadoCORE(INTEGRACION.coreSR.UpdateEmpleadoCORERequest request) {
            return base.Channel.UpdateEmpleadoCORE(request);
        }
        
        public string UpdateEmpleadoCORE(int cuentasCobradas, string Cedula) {
            INTEGRACION.coreSR.UpdateEmpleadoCORERequest inValue = new INTEGRACION.coreSR.UpdateEmpleadoCORERequest();
            inValue.Body = new INTEGRACION.coreSR.UpdateEmpleadoCORERequestBody();
            inValue.Body.cuentasCobradas = cuentasCobradas;
            inValue.Body.Cedula = Cedula;
            INTEGRACION.coreSR.UpdateEmpleadoCOREResponse retVal = ((INTEGRACION.coreSR.coreWSSoap)(this)).UpdateEmpleadoCORE(inValue);
            return retVal.Body.UpdateEmpleadoCOREResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<INTEGRACION.coreSR.UpdateEmpleadoCOREResponse> INTEGRACION.coreSR.coreWSSoap.UpdateEmpleadoCOREAsync(INTEGRACION.coreSR.UpdateEmpleadoCORERequest request) {
            return base.Channel.UpdateEmpleadoCOREAsync(request);
        }
        
        public System.Threading.Tasks.Task<INTEGRACION.coreSR.UpdateEmpleadoCOREResponse> UpdateEmpleadoCOREAsync(int cuentasCobradas, string Cedula) {
            INTEGRACION.coreSR.UpdateEmpleadoCORERequest inValue = new INTEGRACION.coreSR.UpdateEmpleadoCORERequest();
            inValue.Body = new INTEGRACION.coreSR.UpdateEmpleadoCORERequestBody();
            inValue.Body.cuentasCobradas = cuentasCobradas;
            inValue.Body.Cedula = Cedula;
            return ((INTEGRACION.coreSR.coreWSSoap)(this)).UpdateEmpleadoCOREAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        INTEGRACION.coreSR.UpdateProductoCOREResponse INTEGRACION.coreSR.coreWSSoap.UpdateProductoCORE(INTEGRACION.coreSR.UpdateProductoCORERequest request) {
            return base.Channel.UpdateProductoCORE(request);
        }
        
        public string UpdateProductoCORE(string codigo, string usuarioCedula) {
            INTEGRACION.coreSR.UpdateProductoCORERequest inValue = new INTEGRACION.coreSR.UpdateProductoCORERequest();
            inValue.Body = new INTEGRACION.coreSR.UpdateProductoCORERequestBody();
            inValue.Body.codigo = codigo;
            inValue.Body.usuarioCedula = usuarioCedula;
            INTEGRACION.coreSR.UpdateProductoCOREResponse retVal = ((INTEGRACION.coreSR.coreWSSoap)(this)).UpdateProductoCORE(inValue);
            return retVal.Body.UpdateProductoCOREResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<INTEGRACION.coreSR.UpdateProductoCOREResponse> INTEGRACION.coreSR.coreWSSoap.UpdateProductoCOREAsync(INTEGRACION.coreSR.UpdateProductoCORERequest request) {
            return base.Channel.UpdateProductoCOREAsync(request);
        }
        
        public System.Threading.Tasks.Task<INTEGRACION.coreSR.UpdateProductoCOREResponse> UpdateProductoCOREAsync(string codigo, string usuarioCedula) {
            INTEGRACION.coreSR.UpdateProductoCORERequest inValue = new INTEGRACION.coreSR.UpdateProductoCORERequest();
            inValue.Body = new INTEGRACION.coreSR.UpdateProductoCORERequestBody();
            inValue.Body.codigo = codigo;
            inValue.Body.usuarioCedula = usuarioCedula;
            return ((INTEGRACION.coreSR.coreWSSoap)(this)).UpdateProductoCOREAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        INTEGRACION.coreSR.InsertClienteCOREResponse INTEGRACION.coreSR.coreWSSoap.InsertClienteCORE(INTEGRACION.coreSR.InsertClienteCORERequest request) {
            return base.Channel.InsertClienteCORE(request);
        }
        
        public string InsertClienteCORE(string Nombres, string Apellidos, string Cedula, string Telefono, System.DateTime fechaNacimiento, string Email, string Password, string Sexo) {
            INTEGRACION.coreSR.InsertClienteCORERequest inValue = new INTEGRACION.coreSR.InsertClienteCORERequest();
            inValue.Body = new INTEGRACION.coreSR.InsertClienteCORERequestBody();
            inValue.Body.Nombres = Nombres;
            inValue.Body.Apellidos = Apellidos;
            inValue.Body.Cedula = Cedula;
            inValue.Body.Telefono = Telefono;
            inValue.Body.fechaNacimiento = fechaNacimiento;
            inValue.Body.Email = Email;
            inValue.Body.Password = Password;
            inValue.Body.Sexo = Sexo;
            INTEGRACION.coreSR.InsertClienteCOREResponse retVal = ((INTEGRACION.coreSR.coreWSSoap)(this)).InsertClienteCORE(inValue);
            return retVal.Body.InsertClienteCOREResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<INTEGRACION.coreSR.InsertClienteCOREResponse> INTEGRACION.coreSR.coreWSSoap.InsertClienteCOREAsync(INTEGRACION.coreSR.InsertClienteCORERequest request) {
            return base.Channel.InsertClienteCOREAsync(request);
        }
        
        public System.Threading.Tasks.Task<INTEGRACION.coreSR.InsertClienteCOREResponse> InsertClienteCOREAsync(string Nombres, string Apellidos, string Cedula, string Telefono, System.DateTime fechaNacimiento, string Email, string Password, string Sexo) {
            INTEGRACION.coreSR.InsertClienteCORERequest inValue = new INTEGRACION.coreSR.InsertClienteCORERequest();
            inValue.Body = new INTEGRACION.coreSR.InsertClienteCORERequestBody();
            inValue.Body.Nombres = Nombres;
            inValue.Body.Apellidos = Apellidos;
            inValue.Body.Cedula = Cedula;
            inValue.Body.Telefono = Telefono;
            inValue.Body.fechaNacimiento = fechaNacimiento;
            inValue.Body.Email = Email;
            inValue.Body.Password = Password;
            inValue.Body.Sexo = Sexo;
            return ((INTEGRACION.coreSR.coreWSSoap)(this)).InsertClienteCOREAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        INTEGRACION.coreSR.InsertCuentaCOREResponse INTEGRACION.coreSR.coreWSSoap.InsertCuentaCORE(INTEGRACION.coreSR.InsertCuentaCORERequest request) {
            return base.Channel.InsertCuentaCORE(request);
        }
        
        public string InsertCuentaCORE(string Nombres, string Apellidos, string Producto, decimal Total, string cuentaID, string Cedula) {
            INTEGRACION.coreSR.InsertCuentaCORERequest inValue = new INTEGRACION.coreSR.InsertCuentaCORERequest();
            inValue.Body = new INTEGRACION.coreSR.InsertCuentaCORERequestBody();
            inValue.Body.Nombres = Nombres;
            inValue.Body.Apellidos = Apellidos;
            inValue.Body.Producto = Producto;
            inValue.Body.Total = Total;
            inValue.Body.cuentaID = cuentaID;
            inValue.Body.Cedula = Cedula;
            INTEGRACION.coreSR.InsertCuentaCOREResponse retVal = ((INTEGRACION.coreSR.coreWSSoap)(this)).InsertCuentaCORE(inValue);
            return retVal.Body.InsertCuentaCOREResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<INTEGRACION.coreSR.InsertCuentaCOREResponse> INTEGRACION.coreSR.coreWSSoap.InsertCuentaCOREAsync(INTEGRACION.coreSR.InsertCuentaCORERequest request) {
            return base.Channel.InsertCuentaCOREAsync(request);
        }
        
        public System.Threading.Tasks.Task<INTEGRACION.coreSR.InsertCuentaCOREResponse> InsertCuentaCOREAsync(string Nombres, string Apellidos, string Producto, decimal Total, string cuentaID, string Cedula) {
            INTEGRACION.coreSR.InsertCuentaCORERequest inValue = new INTEGRACION.coreSR.InsertCuentaCORERequest();
            inValue.Body = new INTEGRACION.coreSR.InsertCuentaCORERequestBody();
            inValue.Body.Nombres = Nombres;
            inValue.Body.Apellidos = Apellidos;
            inValue.Body.Producto = Producto;
            inValue.Body.Total = Total;
            inValue.Body.cuentaID = cuentaID;
            inValue.Body.Cedula = Cedula;
            return ((INTEGRACION.coreSR.coreWSSoap)(this)).InsertCuentaCOREAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        INTEGRACION.coreSR.DeleteCuentaCOREResponse INTEGRACION.coreSR.coreWSSoap.DeleteCuentaCORE(INTEGRACION.coreSR.DeleteCuentaCORERequest request) {
            return base.Channel.DeleteCuentaCORE(request);
        }
        
        public string DeleteCuentaCORE(string cuentaID) {
            INTEGRACION.coreSR.DeleteCuentaCORERequest inValue = new INTEGRACION.coreSR.DeleteCuentaCORERequest();
            inValue.Body = new INTEGRACION.coreSR.DeleteCuentaCORERequestBody();
            inValue.Body.cuentaID = cuentaID;
            INTEGRACION.coreSR.DeleteCuentaCOREResponse retVal = ((INTEGRACION.coreSR.coreWSSoap)(this)).DeleteCuentaCORE(inValue);
            return retVal.Body.DeleteCuentaCOREResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<INTEGRACION.coreSR.DeleteCuentaCOREResponse> INTEGRACION.coreSR.coreWSSoap.DeleteCuentaCOREAsync(INTEGRACION.coreSR.DeleteCuentaCORERequest request) {
            return base.Channel.DeleteCuentaCOREAsync(request);
        }
        
        public System.Threading.Tasks.Task<INTEGRACION.coreSR.DeleteCuentaCOREResponse> DeleteCuentaCOREAsync(string cuentaID) {
            INTEGRACION.coreSR.DeleteCuentaCORERequest inValue = new INTEGRACION.coreSR.DeleteCuentaCORERequest();
            inValue.Body = new INTEGRACION.coreSR.DeleteCuentaCORERequestBody();
            inValue.Body.cuentaID = cuentaID;
            return ((INTEGRACION.coreSR.coreWSSoap)(this)).DeleteCuentaCOREAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        INTEGRACION.coreSR.InsertFacturaCOREResponse INTEGRACION.coreSR.coreWSSoap.InsertFacturaCORE(INTEGRACION.coreSR.InsertFacturaCORERequest request) {
            return base.Channel.InsertFacturaCORE(request);
        }
        
        public string InsertFacturaCORE(string Nombres, string Apellidos, string Producto, decimal Total, string cuentaID, string Cedula, string facturadoPor) {
            INTEGRACION.coreSR.InsertFacturaCORERequest inValue = new INTEGRACION.coreSR.InsertFacturaCORERequest();
            inValue.Body = new INTEGRACION.coreSR.InsertFacturaCORERequestBody();
            inValue.Body.Nombres = Nombres;
            inValue.Body.Apellidos = Apellidos;
            inValue.Body.Producto = Producto;
            inValue.Body.Total = Total;
            inValue.Body.cuentaID = cuentaID;
            inValue.Body.Cedula = Cedula;
            inValue.Body.facturadoPor = facturadoPor;
            INTEGRACION.coreSR.InsertFacturaCOREResponse retVal = ((INTEGRACION.coreSR.coreWSSoap)(this)).InsertFacturaCORE(inValue);
            return retVal.Body.InsertFacturaCOREResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<INTEGRACION.coreSR.InsertFacturaCOREResponse> INTEGRACION.coreSR.coreWSSoap.InsertFacturaCOREAsync(INTEGRACION.coreSR.InsertFacturaCORERequest request) {
            return base.Channel.InsertFacturaCOREAsync(request);
        }
        
        public System.Threading.Tasks.Task<INTEGRACION.coreSR.InsertFacturaCOREResponse> InsertFacturaCOREAsync(string Nombres, string Apellidos, string Producto, decimal Total, string cuentaID, string Cedula, string facturadoPor) {
            INTEGRACION.coreSR.InsertFacturaCORERequest inValue = new INTEGRACION.coreSR.InsertFacturaCORERequest();
            inValue.Body = new INTEGRACION.coreSR.InsertFacturaCORERequestBody();
            inValue.Body.Nombres = Nombres;
            inValue.Body.Apellidos = Apellidos;
            inValue.Body.Producto = Producto;
            inValue.Body.Total = Total;
            inValue.Body.cuentaID = cuentaID;
            inValue.Body.Cedula = Cedula;
            inValue.Body.facturadoPor = facturadoPor;
            return ((INTEGRACION.coreSR.coreWSSoap)(this)).InsertFacturaCOREAsync(inValue);
        }
    }
}
