//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CORE.integracionSR {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://intec.edu.do", ConfigurationName="integracionSR.integracionSWSoap")]
    public interface integracionSWSoap {
        
        // CODEGEN: Generating message contract since element name Nombre from namespace http://intec.edu.do is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://intec.edu.do/InsertarProductoINTEGRACION", ReplyAction="*")]
        CORE.integracionSR.InsertarProductoINTEGRACIONResponse InsertarProductoINTEGRACION(CORE.integracionSR.InsertarProductoINTEGRACIONRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://intec.edu.do/InsertarProductoINTEGRACION", ReplyAction="*")]
        System.Threading.Tasks.Task<CORE.integracionSR.InsertarProductoINTEGRACIONResponse> InsertarProductoINTEGRACIONAsync(CORE.integracionSR.InsertarProductoINTEGRACIONRequest request);
        
        // CODEGEN: Generating message contract since element name productoID from namespace http://intec.edu.do is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://intec.edu.do/DeleteProductoINTEGRACION", ReplyAction="*")]
        CORE.integracionSR.DeleteProductoINTEGRACIONResponse DeleteProductoINTEGRACION(CORE.integracionSR.DeleteProductoINTEGRACIONRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://intec.edu.do/DeleteProductoINTEGRACION", ReplyAction="*")]
        System.Threading.Tasks.Task<CORE.integracionSR.DeleteProductoINTEGRACIONResponse> DeleteProductoINTEGRACIONAsync(CORE.integracionSR.DeleteProductoINTEGRACIONRequest request);
        
        // CODEGEN: Generating message contract since element name productoID from namespace http://intec.edu.do is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://intec.edu.do/UpdateProductoINTEGRACION", ReplyAction="*")]
        CORE.integracionSR.UpdateProductoINTEGRACIONResponse UpdateProductoINTEGRACION(CORE.integracionSR.UpdateProductoINTEGRACIONRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://intec.edu.do/UpdateProductoINTEGRACION", ReplyAction="*")]
        System.Threading.Tasks.Task<CORE.integracionSR.UpdateProductoINTEGRACIONResponse> UpdateProductoINTEGRACIONAsync(CORE.integracionSR.UpdateProductoINTEGRACIONRequest request);
        
        // CODEGEN: Generating message contract since element name Nombres from namespace http://intec.edu.do is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://intec.edu.do/InsertClienteINTEGRACION", ReplyAction="*")]
        CORE.integracionSR.InsertClienteINTEGRACIONResponse InsertClienteINTEGRACION(CORE.integracionSR.InsertClienteINTEGRACIONRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://intec.edu.do/InsertClienteINTEGRACION", ReplyAction="*")]
        System.Threading.Tasks.Task<CORE.integracionSR.InsertClienteINTEGRACIONResponse> InsertClienteINTEGRACIONAsync(CORE.integracionSR.InsertClienteINTEGRACIONRequest request);
        
        // CODEGEN: Generating message contract since element name Cedula from namespace http://intec.edu.do is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://intec.edu.do/DeleteClienteINTEGRACION", ReplyAction="*")]
        CORE.integracionSR.DeleteClienteINTEGRACIONResponse DeleteClienteINTEGRACION(CORE.integracionSR.DeleteClienteINTEGRACIONRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://intec.edu.do/DeleteClienteINTEGRACION", ReplyAction="*")]
        System.Threading.Tasks.Task<CORE.integracionSR.DeleteClienteINTEGRACIONResponse> DeleteClienteINTEGRACIONAsync(CORE.integracionSR.DeleteClienteINTEGRACIONRequest request);
        
        // CODEGEN: Generating message contract since element name Cedula from namespace http://intec.edu.do is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://intec.edu.do/UpdateClienteINTEGRACION", ReplyAction="*")]
        CORE.integracionSR.UpdateClienteINTEGRACIONResponse UpdateClienteINTEGRACION(CORE.integracionSR.UpdateClienteINTEGRACIONRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://intec.edu.do/UpdateClienteINTEGRACION", ReplyAction="*")]
        System.Threading.Tasks.Task<CORE.integracionSR.UpdateClienteINTEGRACIONResponse> UpdateClienteINTEGRACIONAsync(CORE.integracionSR.UpdateClienteINTEGRACIONRequest request);
        
        // CODEGEN: Generating message contract since element name Nombres from namespace http://intec.edu.do is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://intec.edu.do/InsertEmpleadoINTEGRACION", ReplyAction="*")]
        CORE.integracionSR.InsertEmpleadoINTEGRACIONResponse InsertEmpleadoINTEGRACION(CORE.integracionSR.InsertEmpleadoINTEGRACIONRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://intec.edu.do/InsertEmpleadoINTEGRACION", ReplyAction="*")]
        System.Threading.Tasks.Task<CORE.integracionSR.InsertEmpleadoINTEGRACIONResponse> InsertEmpleadoINTEGRACIONAsync(CORE.integracionSR.InsertEmpleadoINTEGRACIONRequest request);
        
        // CODEGEN: Generating message contract since element name Cedula from namespace http://intec.edu.do is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://intec.edu.do/DeleteEmpleadoINTEGRACION", ReplyAction="*")]
        CORE.integracionSR.DeleteEmpleadoINTEGRACIONResponse DeleteEmpleadoINTEGRACION(CORE.integracionSR.DeleteEmpleadoINTEGRACIONRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://intec.edu.do/DeleteEmpleadoINTEGRACION", ReplyAction="*")]
        System.Threading.Tasks.Task<CORE.integracionSR.DeleteEmpleadoINTEGRACIONResponse> DeleteEmpleadoINTEGRACIONAsync(CORE.integracionSR.DeleteEmpleadoINTEGRACIONRequest request);
        
        // CODEGEN: Generating message contract since element name Cedula from namespace http://intec.edu.do is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://intec.edu.do/UpdateEmpleadoINTEGRACION", ReplyAction="*")]
        CORE.integracionSR.UpdateEmpleadoINTEGRACIONResponse UpdateEmpleadoINTEGRACION(CORE.integracionSR.UpdateEmpleadoINTEGRACIONRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://intec.edu.do/UpdateEmpleadoINTEGRACION", ReplyAction="*")]
        System.Threading.Tasks.Task<CORE.integracionSR.UpdateEmpleadoINTEGRACIONResponse> UpdateEmpleadoINTEGRACIONAsync(CORE.integracionSR.UpdateEmpleadoINTEGRACIONRequest request);
        
        // CODEGEN: Generating message contract since element name Nombres from namespace http://intec.edu.do is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://intec.edu.do/InsertCuentaINTEGRACION", ReplyAction="*")]
        CORE.integracionSR.InsertCuentaINTEGRACIONResponse InsertCuentaINTEGRACION(CORE.integracionSR.InsertCuentaINTEGRACIONRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://intec.edu.do/InsertCuentaINTEGRACION", ReplyAction="*")]
        System.Threading.Tasks.Task<CORE.integracionSR.InsertCuentaINTEGRACIONResponse> InsertCuentaINTEGRACIONAsync(CORE.integracionSR.InsertCuentaINTEGRACIONRequest request);
        
        // CODEGEN: Generating message contract since element name cuentaID from namespace http://intec.edu.do is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://intec.edu.do/DeleteCuentaINTEGRACION", ReplyAction="*")]
        CORE.integracionSR.DeleteCuentaINTEGRACIONResponse DeleteCuentaINTEGRACION(CORE.integracionSR.DeleteCuentaINTEGRACIONRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://intec.edu.do/DeleteCuentaINTEGRACION", ReplyAction="*")]
        System.Threading.Tasks.Task<CORE.integracionSR.DeleteCuentaINTEGRACIONResponse> DeleteCuentaINTEGRACIONAsync(CORE.integracionSR.DeleteCuentaINTEGRACIONRequest request);
        
        // CODEGEN: Generating message contract since element name Nombres from namespace http://intec.edu.do is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://intec.edu.do/InsertFacturaINTEGRACION", ReplyAction="*")]
        CORE.integracionSR.InsertFacturaINTEGRACIONResponse InsertFacturaINTEGRACION(CORE.integracionSR.InsertFacturaINTEGRACIONRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://intec.edu.do/InsertFacturaINTEGRACION", ReplyAction="*")]
        System.Threading.Tasks.Task<CORE.integracionSR.InsertFacturaINTEGRACIONResponse> InsertFacturaINTEGRACIONAsync(CORE.integracionSR.InsertFacturaINTEGRACIONRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertarProductoINTEGRACIONRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertarProductoINTEGRACION", Namespace="http://intec.edu.do", Order=0)]
        public CORE.integracionSR.InsertarProductoINTEGRACIONRequestBody Body;
        
        public InsertarProductoINTEGRACIONRequest() {
        }
        
        public InsertarProductoINTEGRACIONRequest(CORE.integracionSR.InsertarProductoINTEGRACIONRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://intec.edu.do")]
    public partial class InsertarProductoINTEGRACIONRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Nombre;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Tipo;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public decimal Precio;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int Cantidad;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string productoID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Descripcion;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string Marca;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string Imagen;
        
        public InsertarProductoINTEGRACIONRequestBody() {
        }
        
        public InsertarProductoINTEGRACIONRequestBody(string Nombre, string Tipo, decimal Precio, int Cantidad, string productoID, string Descripcion, string Marca, string Imagen) {
            this.Nombre = Nombre;
            this.Tipo = Tipo;
            this.Precio = Precio;
            this.Cantidad = Cantidad;
            this.productoID = productoID;
            this.Descripcion = Descripcion;
            this.Marca = Marca;
            this.Imagen = Imagen;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertarProductoINTEGRACIONResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertarProductoINTEGRACIONResponse", Namespace="http://intec.edu.do", Order=0)]
        public CORE.integracionSR.InsertarProductoINTEGRACIONResponseBody Body;
        
        public InsertarProductoINTEGRACIONResponse() {
        }
        
        public InsertarProductoINTEGRACIONResponse(CORE.integracionSR.InsertarProductoINTEGRACIONResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://intec.edu.do")]
    public partial class InsertarProductoINTEGRACIONResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string InsertarProductoINTEGRACIONResult;
        
        public InsertarProductoINTEGRACIONResponseBody() {
        }
        
        public InsertarProductoINTEGRACIONResponseBody(string InsertarProductoINTEGRACIONResult) {
            this.InsertarProductoINTEGRACIONResult = InsertarProductoINTEGRACIONResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteProductoINTEGRACIONRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteProductoINTEGRACION", Namespace="http://intec.edu.do", Order=0)]
        public CORE.integracionSR.DeleteProductoINTEGRACIONRequestBody Body;
        
        public DeleteProductoINTEGRACIONRequest() {
        }
        
        public DeleteProductoINTEGRACIONRequest(CORE.integracionSR.DeleteProductoINTEGRACIONRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://intec.edu.do")]
    public partial class DeleteProductoINTEGRACIONRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string productoID;
        
        public DeleteProductoINTEGRACIONRequestBody() {
        }
        
        public DeleteProductoINTEGRACIONRequestBody(string productoID) {
            this.productoID = productoID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteProductoINTEGRACIONResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteProductoINTEGRACIONResponse", Namespace="http://intec.edu.do", Order=0)]
        public CORE.integracionSR.DeleteProductoINTEGRACIONResponseBody Body;
        
        public DeleteProductoINTEGRACIONResponse() {
        }
        
        public DeleteProductoINTEGRACIONResponse(CORE.integracionSR.DeleteProductoINTEGRACIONResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://intec.edu.do")]
    public partial class DeleteProductoINTEGRACIONResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string DeleteProductoINTEGRACIONResult;
        
        public DeleteProductoINTEGRACIONResponseBody() {
        }
        
        public DeleteProductoINTEGRACIONResponseBody(string DeleteProductoINTEGRACIONResult) {
            this.DeleteProductoINTEGRACIONResult = DeleteProductoINTEGRACIONResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateProductoINTEGRACIONRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateProductoINTEGRACION", Namespace="http://intec.edu.do", Order=0)]
        public CORE.integracionSR.UpdateProductoINTEGRACIONRequestBody Body;
        
        public UpdateProductoINTEGRACIONRequest() {
        }
        
        public UpdateProductoINTEGRACIONRequest(CORE.integracionSR.UpdateProductoINTEGRACIONRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://intec.edu.do")]
    public partial class UpdateProductoINTEGRACIONRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int Cantidad;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string productoID;
        
        public UpdateProductoINTEGRACIONRequestBody() {
        }
        
        public UpdateProductoINTEGRACIONRequestBody(int Cantidad, string productoID) {
            this.Cantidad = Cantidad;
            this.productoID = productoID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateProductoINTEGRACIONResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateProductoINTEGRACIONResponse", Namespace="http://intec.edu.do", Order=0)]
        public CORE.integracionSR.UpdateProductoINTEGRACIONResponseBody Body;
        
        public UpdateProductoINTEGRACIONResponse() {
        }
        
        public UpdateProductoINTEGRACIONResponse(CORE.integracionSR.UpdateProductoINTEGRACIONResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://intec.edu.do")]
    public partial class UpdateProductoINTEGRACIONResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UpdateProductoINTEGRACIONResult;
        
        public UpdateProductoINTEGRACIONResponseBody() {
        }
        
        public UpdateProductoINTEGRACIONResponseBody(string UpdateProductoINTEGRACIONResult) {
            this.UpdateProductoINTEGRACIONResult = UpdateProductoINTEGRACIONResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertClienteINTEGRACIONRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertClienteINTEGRACION", Namespace="http://intec.edu.do", Order=0)]
        public CORE.integracionSR.InsertClienteINTEGRACIONRequestBody Body;
        
        public InsertClienteINTEGRACIONRequest() {
        }
        
        public InsertClienteINTEGRACIONRequest(CORE.integracionSR.InsertClienteINTEGRACIONRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://intec.edu.do")]
    public partial class InsertClienteINTEGRACIONRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Nombres;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Apellidos;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Cedula;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Telefono;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public System.DateTime fechaNacimiento;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Email;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string Password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string Sexo;
        
        public InsertClienteINTEGRACIONRequestBody() {
        }
        
        public InsertClienteINTEGRACIONRequestBody(string Nombres, string Apellidos, string Cedula, string Telefono, System.DateTime fechaNacimiento, string Email, string Password, string Sexo) {
            this.Nombres = Nombres;
            this.Apellidos = Apellidos;
            this.Cedula = Cedula;
            this.Telefono = Telefono;
            this.fechaNacimiento = fechaNacimiento;
            this.Email = Email;
            this.Password = Password;
            this.Sexo = Sexo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertClienteINTEGRACIONResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertClienteINTEGRACIONResponse", Namespace="http://intec.edu.do", Order=0)]
        public CORE.integracionSR.InsertClienteINTEGRACIONResponseBody Body;
        
        public InsertClienteINTEGRACIONResponse() {
        }
        
        public InsertClienteINTEGRACIONResponse(CORE.integracionSR.InsertClienteINTEGRACIONResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://intec.edu.do")]
    public partial class InsertClienteINTEGRACIONResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string InsertClienteINTEGRACIONResult;
        
        public InsertClienteINTEGRACIONResponseBody() {
        }
        
        public InsertClienteINTEGRACIONResponseBody(string InsertClienteINTEGRACIONResult) {
            this.InsertClienteINTEGRACIONResult = InsertClienteINTEGRACIONResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteClienteINTEGRACIONRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteClienteINTEGRACION", Namespace="http://intec.edu.do", Order=0)]
        public CORE.integracionSR.DeleteClienteINTEGRACIONRequestBody Body;
        
        public DeleteClienteINTEGRACIONRequest() {
        }
        
        public DeleteClienteINTEGRACIONRequest(CORE.integracionSR.DeleteClienteINTEGRACIONRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://intec.edu.do")]
    public partial class DeleteClienteINTEGRACIONRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Cedula;
        
        public DeleteClienteINTEGRACIONRequestBody() {
        }
        
        public DeleteClienteINTEGRACIONRequestBody(string Cedula) {
            this.Cedula = Cedula;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteClienteINTEGRACIONResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteClienteINTEGRACIONResponse", Namespace="http://intec.edu.do", Order=0)]
        public CORE.integracionSR.DeleteClienteINTEGRACIONResponseBody Body;
        
        public DeleteClienteINTEGRACIONResponse() {
        }
        
        public DeleteClienteINTEGRACIONResponse(CORE.integracionSR.DeleteClienteINTEGRACIONResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://intec.edu.do")]
    public partial class DeleteClienteINTEGRACIONResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string DeleteClienteINTEGRACIONResult;
        
        public DeleteClienteINTEGRACIONResponseBody() {
        }
        
        public DeleteClienteINTEGRACIONResponseBody(string DeleteClienteINTEGRACIONResult) {
            this.DeleteClienteINTEGRACIONResult = DeleteClienteINTEGRACIONResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateClienteINTEGRACIONRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateClienteINTEGRACION", Namespace="http://intec.edu.do", Order=0)]
        public CORE.integracionSR.UpdateClienteINTEGRACIONRequestBody Body;
        
        public UpdateClienteINTEGRACIONRequest() {
        }
        
        public UpdateClienteINTEGRACIONRequest(CORE.integracionSR.UpdateClienteINTEGRACIONRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://intec.edu.do")]
    public partial class UpdateClienteINTEGRACIONRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public decimal totalGastado;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Cedula;
        
        public UpdateClienteINTEGRACIONRequestBody() {
        }
        
        public UpdateClienteINTEGRACIONRequestBody(decimal totalGastado, string Cedula) {
            this.totalGastado = totalGastado;
            this.Cedula = Cedula;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateClienteINTEGRACIONResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateClienteINTEGRACIONResponse", Namespace="http://intec.edu.do", Order=0)]
        public CORE.integracionSR.UpdateClienteINTEGRACIONResponseBody Body;
        
        public UpdateClienteINTEGRACIONResponse() {
        }
        
        public UpdateClienteINTEGRACIONResponse(CORE.integracionSR.UpdateClienteINTEGRACIONResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://intec.edu.do")]
    public partial class UpdateClienteINTEGRACIONResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UpdateClienteINTEGRACIONResult;
        
        public UpdateClienteINTEGRACIONResponseBody() {
        }
        
        public UpdateClienteINTEGRACIONResponseBody(string UpdateClienteINTEGRACIONResult) {
            this.UpdateClienteINTEGRACIONResult = UpdateClienteINTEGRACIONResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertEmpleadoINTEGRACIONRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertEmpleadoINTEGRACION", Namespace="http://intec.edu.do", Order=0)]
        public CORE.integracionSR.InsertEmpleadoINTEGRACIONRequestBody Body;
        
        public InsertEmpleadoINTEGRACIONRequest() {
        }
        
        public InsertEmpleadoINTEGRACIONRequest(CORE.integracionSR.InsertEmpleadoINTEGRACIONRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://intec.edu.do")]
    public partial class InsertEmpleadoINTEGRACIONRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Nombres;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Apellidos;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Cedula;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Telefono;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string rol;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Email;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string Password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string Sexo;
        
        public InsertEmpleadoINTEGRACIONRequestBody() {
        }
        
        public InsertEmpleadoINTEGRACIONRequestBody(string Nombres, string Apellidos, string Cedula, string Telefono, string rol, string Email, string Password, string Sexo) {
            this.Nombres = Nombres;
            this.Apellidos = Apellidos;
            this.Cedula = Cedula;
            this.Telefono = Telefono;
            this.rol = rol;
            this.Email = Email;
            this.Password = Password;
            this.Sexo = Sexo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertEmpleadoINTEGRACIONResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertEmpleadoINTEGRACIONResponse", Namespace="http://intec.edu.do", Order=0)]
        public CORE.integracionSR.InsertEmpleadoINTEGRACIONResponseBody Body;
        
        public InsertEmpleadoINTEGRACIONResponse() {
        }
        
        public InsertEmpleadoINTEGRACIONResponse(CORE.integracionSR.InsertEmpleadoINTEGRACIONResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://intec.edu.do")]
    public partial class InsertEmpleadoINTEGRACIONResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string InsertEmpleadoINTEGRACIONResult;
        
        public InsertEmpleadoINTEGRACIONResponseBody() {
        }
        
        public InsertEmpleadoINTEGRACIONResponseBody(string InsertEmpleadoINTEGRACIONResult) {
            this.InsertEmpleadoINTEGRACIONResult = InsertEmpleadoINTEGRACIONResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteEmpleadoINTEGRACIONRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteEmpleadoINTEGRACION", Namespace="http://intec.edu.do", Order=0)]
        public CORE.integracionSR.DeleteEmpleadoINTEGRACIONRequestBody Body;
        
        public DeleteEmpleadoINTEGRACIONRequest() {
        }
        
        public DeleteEmpleadoINTEGRACIONRequest(CORE.integracionSR.DeleteEmpleadoINTEGRACIONRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://intec.edu.do")]
    public partial class DeleteEmpleadoINTEGRACIONRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Cedula;
        
        public DeleteEmpleadoINTEGRACIONRequestBody() {
        }
        
        public DeleteEmpleadoINTEGRACIONRequestBody(string Cedula) {
            this.Cedula = Cedula;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteEmpleadoINTEGRACIONResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteEmpleadoINTEGRACIONResponse", Namespace="http://intec.edu.do", Order=0)]
        public CORE.integracionSR.DeleteEmpleadoINTEGRACIONResponseBody Body;
        
        public DeleteEmpleadoINTEGRACIONResponse() {
        }
        
        public DeleteEmpleadoINTEGRACIONResponse(CORE.integracionSR.DeleteEmpleadoINTEGRACIONResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://intec.edu.do")]
    public partial class DeleteEmpleadoINTEGRACIONResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string DeleteEmpleadoINTEGRACIONResult;
        
        public DeleteEmpleadoINTEGRACIONResponseBody() {
        }
        
        public DeleteEmpleadoINTEGRACIONResponseBody(string DeleteEmpleadoINTEGRACIONResult) {
            this.DeleteEmpleadoINTEGRACIONResult = DeleteEmpleadoINTEGRACIONResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateEmpleadoINTEGRACIONRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateEmpleadoINTEGRACION", Namespace="http://intec.edu.do", Order=0)]
        public CORE.integracionSR.UpdateEmpleadoINTEGRACIONRequestBody Body;
        
        public UpdateEmpleadoINTEGRACIONRequest() {
        }
        
        public UpdateEmpleadoINTEGRACIONRequest(CORE.integracionSR.UpdateEmpleadoINTEGRACIONRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://intec.edu.do")]
    public partial class UpdateEmpleadoINTEGRACIONRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int cuentasCobradas;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Cedula;
        
        public UpdateEmpleadoINTEGRACIONRequestBody() {
        }
        
        public UpdateEmpleadoINTEGRACIONRequestBody(int cuentasCobradas, string Cedula) {
            this.cuentasCobradas = cuentasCobradas;
            this.Cedula = Cedula;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateEmpleadoINTEGRACIONResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateEmpleadoINTEGRACIONResponse", Namespace="http://intec.edu.do", Order=0)]
        public CORE.integracionSR.UpdateEmpleadoINTEGRACIONResponseBody Body;
        
        public UpdateEmpleadoINTEGRACIONResponse() {
        }
        
        public UpdateEmpleadoINTEGRACIONResponse(CORE.integracionSR.UpdateEmpleadoINTEGRACIONResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://intec.edu.do")]
    public partial class UpdateEmpleadoINTEGRACIONResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UpdateEmpleadoINTEGRACIONResult;
        
        public UpdateEmpleadoINTEGRACIONResponseBody() {
        }
        
        public UpdateEmpleadoINTEGRACIONResponseBody(string UpdateEmpleadoINTEGRACIONResult) {
            this.UpdateEmpleadoINTEGRACIONResult = UpdateEmpleadoINTEGRACIONResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertCuentaINTEGRACIONRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertCuentaINTEGRACION", Namespace="http://intec.edu.do", Order=0)]
        public CORE.integracionSR.InsertCuentaINTEGRACIONRequestBody Body;
        
        public InsertCuentaINTEGRACIONRequest() {
        }
        
        public InsertCuentaINTEGRACIONRequest(CORE.integracionSR.InsertCuentaINTEGRACIONRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://intec.edu.do")]
    public partial class InsertCuentaINTEGRACIONRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Nombres;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Apellidos;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Producto;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public decimal Total;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string cuentaID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Cedula;
        
        public InsertCuentaINTEGRACIONRequestBody() {
        }
        
        public InsertCuentaINTEGRACIONRequestBody(string Nombres, string Apellidos, string Producto, decimal Total, string cuentaID, string Cedula) {
            this.Nombres = Nombres;
            this.Apellidos = Apellidos;
            this.Producto = Producto;
            this.Total = Total;
            this.cuentaID = cuentaID;
            this.Cedula = Cedula;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertCuentaINTEGRACIONResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertCuentaINTEGRACIONResponse", Namespace="http://intec.edu.do", Order=0)]
        public CORE.integracionSR.InsertCuentaINTEGRACIONResponseBody Body;
        
        public InsertCuentaINTEGRACIONResponse() {
        }
        
        public InsertCuentaINTEGRACIONResponse(CORE.integracionSR.InsertCuentaINTEGRACIONResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://intec.edu.do")]
    public partial class InsertCuentaINTEGRACIONResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string InsertCuentaINTEGRACIONResult;
        
        public InsertCuentaINTEGRACIONResponseBody() {
        }
        
        public InsertCuentaINTEGRACIONResponseBody(string InsertCuentaINTEGRACIONResult) {
            this.InsertCuentaINTEGRACIONResult = InsertCuentaINTEGRACIONResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteCuentaINTEGRACIONRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteCuentaINTEGRACION", Namespace="http://intec.edu.do", Order=0)]
        public CORE.integracionSR.DeleteCuentaINTEGRACIONRequestBody Body;
        
        public DeleteCuentaINTEGRACIONRequest() {
        }
        
        public DeleteCuentaINTEGRACIONRequest(CORE.integracionSR.DeleteCuentaINTEGRACIONRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://intec.edu.do")]
    public partial class DeleteCuentaINTEGRACIONRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string cuentaID;
        
        public DeleteCuentaINTEGRACIONRequestBody() {
        }
        
        public DeleteCuentaINTEGRACIONRequestBody(string cuentaID) {
            this.cuentaID = cuentaID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteCuentaINTEGRACIONResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteCuentaINTEGRACIONResponse", Namespace="http://intec.edu.do", Order=0)]
        public CORE.integracionSR.DeleteCuentaINTEGRACIONResponseBody Body;
        
        public DeleteCuentaINTEGRACIONResponse() {
        }
        
        public DeleteCuentaINTEGRACIONResponse(CORE.integracionSR.DeleteCuentaINTEGRACIONResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://intec.edu.do")]
    public partial class DeleteCuentaINTEGRACIONResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string DeleteCuentaINTEGRACIONResult;
        
        public DeleteCuentaINTEGRACIONResponseBody() {
        }
        
        public DeleteCuentaINTEGRACIONResponseBody(string DeleteCuentaINTEGRACIONResult) {
            this.DeleteCuentaINTEGRACIONResult = DeleteCuentaINTEGRACIONResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertFacturaINTEGRACIONRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertFacturaINTEGRACION", Namespace="http://intec.edu.do", Order=0)]
        public CORE.integracionSR.InsertFacturaINTEGRACIONRequestBody Body;
        
        public InsertFacturaINTEGRACIONRequest() {
        }
        
        public InsertFacturaINTEGRACIONRequest(CORE.integracionSR.InsertFacturaINTEGRACIONRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://intec.edu.do")]
    public partial class InsertFacturaINTEGRACIONRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Nombres;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Apellidos;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Producto;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public decimal Total;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string cuentaID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Cedula;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string facturadoPor;
        
        public InsertFacturaINTEGRACIONRequestBody() {
        }
        
        public InsertFacturaINTEGRACIONRequestBody(string Nombres, string Apellidos, string Producto, decimal Total, string cuentaID, string Cedula, string facturadoPor) {
            this.Nombres = Nombres;
            this.Apellidos = Apellidos;
            this.Producto = Producto;
            this.Total = Total;
            this.cuentaID = cuentaID;
            this.Cedula = Cedula;
            this.facturadoPor = facturadoPor;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertFacturaINTEGRACIONResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertFacturaINTEGRACIONResponse", Namespace="http://intec.edu.do", Order=0)]
        public CORE.integracionSR.InsertFacturaINTEGRACIONResponseBody Body;
        
        public InsertFacturaINTEGRACIONResponse() {
        }
        
        public InsertFacturaINTEGRACIONResponse(CORE.integracionSR.InsertFacturaINTEGRACIONResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://intec.edu.do")]
    public partial class InsertFacturaINTEGRACIONResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string InsertFacturaINTEGRACIONResult;
        
        public InsertFacturaINTEGRACIONResponseBody() {
        }
        
        public InsertFacturaINTEGRACIONResponseBody(string InsertFacturaINTEGRACIONResult) {
            this.InsertFacturaINTEGRACIONResult = InsertFacturaINTEGRACIONResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface integracionSWSoapChannel : CORE.integracionSR.integracionSWSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class integracionSWSoapClient : System.ServiceModel.ClientBase<CORE.integracionSR.integracionSWSoap>, CORE.integracionSR.integracionSWSoap {
        
        public integracionSWSoapClient() {
        }
        
        public integracionSWSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public integracionSWSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public integracionSWSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public integracionSWSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CORE.integracionSR.InsertarProductoINTEGRACIONResponse CORE.integracionSR.integracionSWSoap.InsertarProductoINTEGRACION(CORE.integracionSR.InsertarProductoINTEGRACIONRequest request) {
            return base.Channel.InsertarProductoINTEGRACION(request);
        }
        
        public string InsertarProductoINTEGRACION(string Nombre, string Tipo, decimal Precio, int Cantidad, string productoID, string Descripcion, string Marca, string Imagen) {
            CORE.integracionSR.InsertarProductoINTEGRACIONRequest inValue = new CORE.integracionSR.InsertarProductoINTEGRACIONRequest();
            inValue.Body = new CORE.integracionSR.InsertarProductoINTEGRACIONRequestBody();
            inValue.Body.Nombre = Nombre;
            inValue.Body.Tipo = Tipo;
            inValue.Body.Precio = Precio;
            inValue.Body.Cantidad = Cantidad;
            inValue.Body.productoID = productoID;
            inValue.Body.Descripcion = Descripcion;
            inValue.Body.Marca = Marca;
            inValue.Body.Imagen = Imagen;
            CORE.integracionSR.InsertarProductoINTEGRACIONResponse retVal = ((CORE.integracionSR.integracionSWSoap)(this)).InsertarProductoINTEGRACION(inValue);
            return retVal.Body.InsertarProductoINTEGRACIONResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CORE.integracionSR.InsertarProductoINTEGRACIONResponse> CORE.integracionSR.integracionSWSoap.InsertarProductoINTEGRACIONAsync(CORE.integracionSR.InsertarProductoINTEGRACIONRequest request) {
            return base.Channel.InsertarProductoINTEGRACIONAsync(request);
        }
        
        public System.Threading.Tasks.Task<CORE.integracionSR.InsertarProductoINTEGRACIONResponse> InsertarProductoINTEGRACIONAsync(string Nombre, string Tipo, decimal Precio, int Cantidad, string productoID, string Descripcion, string Marca, string Imagen) {
            CORE.integracionSR.InsertarProductoINTEGRACIONRequest inValue = new CORE.integracionSR.InsertarProductoINTEGRACIONRequest();
            inValue.Body = new CORE.integracionSR.InsertarProductoINTEGRACIONRequestBody();
            inValue.Body.Nombre = Nombre;
            inValue.Body.Tipo = Tipo;
            inValue.Body.Precio = Precio;
            inValue.Body.Cantidad = Cantidad;
            inValue.Body.productoID = productoID;
            inValue.Body.Descripcion = Descripcion;
            inValue.Body.Marca = Marca;
            inValue.Body.Imagen = Imagen;
            return ((CORE.integracionSR.integracionSWSoap)(this)).InsertarProductoINTEGRACIONAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CORE.integracionSR.DeleteProductoINTEGRACIONResponse CORE.integracionSR.integracionSWSoap.DeleteProductoINTEGRACION(CORE.integracionSR.DeleteProductoINTEGRACIONRequest request) {
            return base.Channel.DeleteProductoINTEGRACION(request);
        }
        
        public string DeleteProductoINTEGRACION(string productoID) {
            CORE.integracionSR.DeleteProductoINTEGRACIONRequest inValue = new CORE.integracionSR.DeleteProductoINTEGRACIONRequest();
            inValue.Body = new CORE.integracionSR.DeleteProductoINTEGRACIONRequestBody();
            inValue.Body.productoID = productoID;
            CORE.integracionSR.DeleteProductoINTEGRACIONResponse retVal = ((CORE.integracionSR.integracionSWSoap)(this)).DeleteProductoINTEGRACION(inValue);
            return retVal.Body.DeleteProductoINTEGRACIONResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CORE.integracionSR.DeleteProductoINTEGRACIONResponse> CORE.integracionSR.integracionSWSoap.DeleteProductoINTEGRACIONAsync(CORE.integracionSR.DeleteProductoINTEGRACIONRequest request) {
            return base.Channel.DeleteProductoINTEGRACIONAsync(request);
        }
        
        public System.Threading.Tasks.Task<CORE.integracionSR.DeleteProductoINTEGRACIONResponse> DeleteProductoINTEGRACIONAsync(string productoID) {
            CORE.integracionSR.DeleteProductoINTEGRACIONRequest inValue = new CORE.integracionSR.DeleteProductoINTEGRACIONRequest();
            inValue.Body = new CORE.integracionSR.DeleteProductoINTEGRACIONRequestBody();
            inValue.Body.productoID = productoID;
            return ((CORE.integracionSR.integracionSWSoap)(this)).DeleteProductoINTEGRACIONAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CORE.integracionSR.UpdateProductoINTEGRACIONResponse CORE.integracionSR.integracionSWSoap.UpdateProductoINTEGRACION(CORE.integracionSR.UpdateProductoINTEGRACIONRequest request) {
            return base.Channel.UpdateProductoINTEGRACION(request);
        }
        
        public string UpdateProductoINTEGRACION(int Cantidad, string productoID) {
            CORE.integracionSR.UpdateProductoINTEGRACIONRequest inValue = new CORE.integracionSR.UpdateProductoINTEGRACIONRequest();
            inValue.Body = new CORE.integracionSR.UpdateProductoINTEGRACIONRequestBody();
            inValue.Body.Cantidad = Cantidad;
            inValue.Body.productoID = productoID;
            CORE.integracionSR.UpdateProductoINTEGRACIONResponse retVal = ((CORE.integracionSR.integracionSWSoap)(this)).UpdateProductoINTEGRACION(inValue);
            return retVal.Body.UpdateProductoINTEGRACIONResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CORE.integracionSR.UpdateProductoINTEGRACIONResponse> CORE.integracionSR.integracionSWSoap.UpdateProductoINTEGRACIONAsync(CORE.integracionSR.UpdateProductoINTEGRACIONRequest request) {
            return base.Channel.UpdateProductoINTEGRACIONAsync(request);
        }
        
        public System.Threading.Tasks.Task<CORE.integracionSR.UpdateProductoINTEGRACIONResponse> UpdateProductoINTEGRACIONAsync(int Cantidad, string productoID) {
            CORE.integracionSR.UpdateProductoINTEGRACIONRequest inValue = new CORE.integracionSR.UpdateProductoINTEGRACIONRequest();
            inValue.Body = new CORE.integracionSR.UpdateProductoINTEGRACIONRequestBody();
            inValue.Body.Cantidad = Cantidad;
            inValue.Body.productoID = productoID;
            return ((CORE.integracionSR.integracionSWSoap)(this)).UpdateProductoINTEGRACIONAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CORE.integracionSR.InsertClienteINTEGRACIONResponse CORE.integracionSR.integracionSWSoap.InsertClienteINTEGRACION(CORE.integracionSR.InsertClienteINTEGRACIONRequest request) {
            return base.Channel.InsertClienteINTEGRACION(request);
        }
        
        public string InsertClienteINTEGRACION(string Nombres, string Apellidos, string Cedula, string Telefono, System.DateTime fechaNacimiento, string Email, string Password, string Sexo) {
            CORE.integracionSR.InsertClienteINTEGRACIONRequest inValue = new CORE.integracionSR.InsertClienteINTEGRACIONRequest();
            inValue.Body = new CORE.integracionSR.InsertClienteINTEGRACIONRequestBody();
            inValue.Body.Nombres = Nombres;
            inValue.Body.Apellidos = Apellidos;
            inValue.Body.Cedula = Cedula;
            inValue.Body.Telefono = Telefono;
            inValue.Body.fechaNacimiento = fechaNacimiento;
            inValue.Body.Email = Email;
            inValue.Body.Password = Password;
            inValue.Body.Sexo = Sexo;
            CORE.integracionSR.InsertClienteINTEGRACIONResponse retVal = ((CORE.integracionSR.integracionSWSoap)(this)).InsertClienteINTEGRACION(inValue);
            return retVal.Body.InsertClienteINTEGRACIONResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CORE.integracionSR.InsertClienteINTEGRACIONResponse> CORE.integracionSR.integracionSWSoap.InsertClienteINTEGRACIONAsync(CORE.integracionSR.InsertClienteINTEGRACIONRequest request) {
            return base.Channel.InsertClienteINTEGRACIONAsync(request);
        }
        
        public System.Threading.Tasks.Task<CORE.integracionSR.InsertClienteINTEGRACIONResponse> InsertClienteINTEGRACIONAsync(string Nombres, string Apellidos, string Cedula, string Telefono, System.DateTime fechaNacimiento, string Email, string Password, string Sexo) {
            CORE.integracionSR.InsertClienteINTEGRACIONRequest inValue = new CORE.integracionSR.InsertClienteINTEGRACIONRequest();
            inValue.Body = new CORE.integracionSR.InsertClienteINTEGRACIONRequestBody();
            inValue.Body.Nombres = Nombres;
            inValue.Body.Apellidos = Apellidos;
            inValue.Body.Cedula = Cedula;
            inValue.Body.Telefono = Telefono;
            inValue.Body.fechaNacimiento = fechaNacimiento;
            inValue.Body.Email = Email;
            inValue.Body.Password = Password;
            inValue.Body.Sexo = Sexo;
            return ((CORE.integracionSR.integracionSWSoap)(this)).InsertClienteINTEGRACIONAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CORE.integracionSR.DeleteClienteINTEGRACIONResponse CORE.integracionSR.integracionSWSoap.DeleteClienteINTEGRACION(CORE.integracionSR.DeleteClienteINTEGRACIONRequest request) {
            return base.Channel.DeleteClienteINTEGRACION(request);
        }
        
        public string DeleteClienteINTEGRACION(string Cedula) {
            CORE.integracionSR.DeleteClienteINTEGRACIONRequest inValue = new CORE.integracionSR.DeleteClienteINTEGRACIONRequest();
            inValue.Body = new CORE.integracionSR.DeleteClienteINTEGRACIONRequestBody();
            inValue.Body.Cedula = Cedula;
            CORE.integracionSR.DeleteClienteINTEGRACIONResponse retVal = ((CORE.integracionSR.integracionSWSoap)(this)).DeleteClienteINTEGRACION(inValue);
            return retVal.Body.DeleteClienteINTEGRACIONResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CORE.integracionSR.DeleteClienteINTEGRACIONResponse> CORE.integracionSR.integracionSWSoap.DeleteClienteINTEGRACIONAsync(CORE.integracionSR.DeleteClienteINTEGRACIONRequest request) {
            return base.Channel.DeleteClienteINTEGRACIONAsync(request);
        }
        
        public System.Threading.Tasks.Task<CORE.integracionSR.DeleteClienteINTEGRACIONResponse> DeleteClienteINTEGRACIONAsync(string Cedula) {
            CORE.integracionSR.DeleteClienteINTEGRACIONRequest inValue = new CORE.integracionSR.DeleteClienteINTEGRACIONRequest();
            inValue.Body = new CORE.integracionSR.DeleteClienteINTEGRACIONRequestBody();
            inValue.Body.Cedula = Cedula;
            return ((CORE.integracionSR.integracionSWSoap)(this)).DeleteClienteINTEGRACIONAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CORE.integracionSR.UpdateClienteINTEGRACIONResponse CORE.integracionSR.integracionSWSoap.UpdateClienteINTEGRACION(CORE.integracionSR.UpdateClienteINTEGRACIONRequest request) {
            return base.Channel.UpdateClienteINTEGRACION(request);
        }
        
        public string UpdateClienteINTEGRACION(decimal totalGastado, string Cedula) {
            CORE.integracionSR.UpdateClienteINTEGRACIONRequest inValue = new CORE.integracionSR.UpdateClienteINTEGRACIONRequest();
            inValue.Body = new CORE.integracionSR.UpdateClienteINTEGRACIONRequestBody();
            inValue.Body.totalGastado = totalGastado;
            inValue.Body.Cedula = Cedula;
            CORE.integracionSR.UpdateClienteINTEGRACIONResponse retVal = ((CORE.integracionSR.integracionSWSoap)(this)).UpdateClienteINTEGRACION(inValue);
            return retVal.Body.UpdateClienteINTEGRACIONResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CORE.integracionSR.UpdateClienteINTEGRACIONResponse> CORE.integracionSR.integracionSWSoap.UpdateClienteINTEGRACIONAsync(CORE.integracionSR.UpdateClienteINTEGRACIONRequest request) {
            return base.Channel.UpdateClienteINTEGRACIONAsync(request);
        }
        
        public System.Threading.Tasks.Task<CORE.integracionSR.UpdateClienteINTEGRACIONResponse> UpdateClienteINTEGRACIONAsync(decimal totalGastado, string Cedula) {
            CORE.integracionSR.UpdateClienteINTEGRACIONRequest inValue = new CORE.integracionSR.UpdateClienteINTEGRACIONRequest();
            inValue.Body = new CORE.integracionSR.UpdateClienteINTEGRACIONRequestBody();
            inValue.Body.totalGastado = totalGastado;
            inValue.Body.Cedula = Cedula;
            return ((CORE.integracionSR.integracionSWSoap)(this)).UpdateClienteINTEGRACIONAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CORE.integracionSR.InsertEmpleadoINTEGRACIONResponse CORE.integracionSR.integracionSWSoap.InsertEmpleadoINTEGRACION(CORE.integracionSR.InsertEmpleadoINTEGRACIONRequest request) {
            return base.Channel.InsertEmpleadoINTEGRACION(request);
        }
        
        public string InsertEmpleadoINTEGRACION(string Nombres, string Apellidos, string Cedula, string Telefono, string rol, string Email, string Password, string Sexo) {
            CORE.integracionSR.InsertEmpleadoINTEGRACIONRequest inValue = new CORE.integracionSR.InsertEmpleadoINTEGRACIONRequest();
            inValue.Body = new CORE.integracionSR.InsertEmpleadoINTEGRACIONRequestBody();
            inValue.Body.Nombres = Nombres;
            inValue.Body.Apellidos = Apellidos;
            inValue.Body.Cedula = Cedula;
            inValue.Body.Telefono = Telefono;
            inValue.Body.rol = rol;
            inValue.Body.Email = Email;
            inValue.Body.Password = Password;
            inValue.Body.Sexo = Sexo;
            CORE.integracionSR.InsertEmpleadoINTEGRACIONResponse retVal = ((CORE.integracionSR.integracionSWSoap)(this)).InsertEmpleadoINTEGRACION(inValue);
            return retVal.Body.InsertEmpleadoINTEGRACIONResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CORE.integracionSR.InsertEmpleadoINTEGRACIONResponse> CORE.integracionSR.integracionSWSoap.InsertEmpleadoINTEGRACIONAsync(CORE.integracionSR.InsertEmpleadoINTEGRACIONRequest request) {
            return base.Channel.InsertEmpleadoINTEGRACIONAsync(request);
        }
        
        public System.Threading.Tasks.Task<CORE.integracionSR.InsertEmpleadoINTEGRACIONResponse> InsertEmpleadoINTEGRACIONAsync(string Nombres, string Apellidos, string Cedula, string Telefono, string rol, string Email, string Password, string Sexo) {
            CORE.integracionSR.InsertEmpleadoINTEGRACIONRequest inValue = new CORE.integracionSR.InsertEmpleadoINTEGRACIONRequest();
            inValue.Body = new CORE.integracionSR.InsertEmpleadoINTEGRACIONRequestBody();
            inValue.Body.Nombres = Nombres;
            inValue.Body.Apellidos = Apellidos;
            inValue.Body.Cedula = Cedula;
            inValue.Body.Telefono = Telefono;
            inValue.Body.rol = rol;
            inValue.Body.Email = Email;
            inValue.Body.Password = Password;
            inValue.Body.Sexo = Sexo;
            return ((CORE.integracionSR.integracionSWSoap)(this)).InsertEmpleadoINTEGRACIONAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CORE.integracionSR.DeleteEmpleadoINTEGRACIONResponse CORE.integracionSR.integracionSWSoap.DeleteEmpleadoINTEGRACION(CORE.integracionSR.DeleteEmpleadoINTEGRACIONRequest request) {
            return base.Channel.DeleteEmpleadoINTEGRACION(request);
        }
        
        public string DeleteEmpleadoINTEGRACION(string Cedula) {
            CORE.integracionSR.DeleteEmpleadoINTEGRACIONRequest inValue = new CORE.integracionSR.DeleteEmpleadoINTEGRACIONRequest();
            inValue.Body = new CORE.integracionSR.DeleteEmpleadoINTEGRACIONRequestBody();
            inValue.Body.Cedula = Cedula;
            CORE.integracionSR.DeleteEmpleadoINTEGRACIONResponse retVal = ((CORE.integracionSR.integracionSWSoap)(this)).DeleteEmpleadoINTEGRACION(inValue);
            return retVal.Body.DeleteEmpleadoINTEGRACIONResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CORE.integracionSR.DeleteEmpleadoINTEGRACIONResponse> CORE.integracionSR.integracionSWSoap.DeleteEmpleadoINTEGRACIONAsync(CORE.integracionSR.DeleteEmpleadoINTEGRACIONRequest request) {
            return base.Channel.DeleteEmpleadoINTEGRACIONAsync(request);
        }
        
        public System.Threading.Tasks.Task<CORE.integracionSR.DeleteEmpleadoINTEGRACIONResponse> DeleteEmpleadoINTEGRACIONAsync(string Cedula) {
            CORE.integracionSR.DeleteEmpleadoINTEGRACIONRequest inValue = new CORE.integracionSR.DeleteEmpleadoINTEGRACIONRequest();
            inValue.Body = new CORE.integracionSR.DeleteEmpleadoINTEGRACIONRequestBody();
            inValue.Body.Cedula = Cedula;
            return ((CORE.integracionSR.integracionSWSoap)(this)).DeleteEmpleadoINTEGRACIONAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CORE.integracionSR.UpdateEmpleadoINTEGRACIONResponse CORE.integracionSR.integracionSWSoap.UpdateEmpleadoINTEGRACION(CORE.integracionSR.UpdateEmpleadoINTEGRACIONRequest request) {
            return base.Channel.UpdateEmpleadoINTEGRACION(request);
        }
        
        public string UpdateEmpleadoINTEGRACION(int cuentasCobradas, string Cedula) {
            CORE.integracionSR.UpdateEmpleadoINTEGRACIONRequest inValue = new CORE.integracionSR.UpdateEmpleadoINTEGRACIONRequest();
            inValue.Body = new CORE.integracionSR.UpdateEmpleadoINTEGRACIONRequestBody();
            inValue.Body.cuentasCobradas = cuentasCobradas;
            inValue.Body.Cedula = Cedula;
            CORE.integracionSR.UpdateEmpleadoINTEGRACIONResponse retVal = ((CORE.integracionSR.integracionSWSoap)(this)).UpdateEmpleadoINTEGRACION(inValue);
            return retVal.Body.UpdateEmpleadoINTEGRACIONResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CORE.integracionSR.UpdateEmpleadoINTEGRACIONResponse> CORE.integracionSR.integracionSWSoap.UpdateEmpleadoINTEGRACIONAsync(CORE.integracionSR.UpdateEmpleadoINTEGRACIONRequest request) {
            return base.Channel.UpdateEmpleadoINTEGRACIONAsync(request);
        }
        
        public System.Threading.Tasks.Task<CORE.integracionSR.UpdateEmpleadoINTEGRACIONResponse> UpdateEmpleadoINTEGRACIONAsync(int cuentasCobradas, string Cedula) {
            CORE.integracionSR.UpdateEmpleadoINTEGRACIONRequest inValue = new CORE.integracionSR.UpdateEmpleadoINTEGRACIONRequest();
            inValue.Body = new CORE.integracionSR.UpdateEmpleadoINTEGRACIONRequestBody();
            inValue.Body.cuentasCobradas = cuentasCobradas;
            inValue.Body.Cedula = Cedula;
            return ((CORE.integracionSR.integracionSWSoap)(this)).UpdateEmpleadoINTEGRACIONAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CORE.integracionSR.InsertCuentaINTEGRACIONResponse CORE.integracionSR.integracionSWSoap.InsertCuentaINTEGRACION(CORE.integracionSR.InsertCuentaINTEGRACIONRequest request) {
            return base.Channel.InsertCuentaINTEGRACION(request);
        }
        
        public string InsertCuentaINTEGRACION(string Nombres, string Apellidos, string Producto, decimal Total, string cuentaID, string Cedula) {
            CORE.integracionSR.InsertCuentaINTEGRACIONRequest inValue = new CORE.integracionSR.InsertCuentaINTEGRACIONRequest();
            inValue.Body = new CORE.integracionSR.InsertCuentaINTEGRACIONRequestBody();
            inValue.Body.Nombres = Nombres;
            inValue.Body.Apellidos = Apellidos;
            inValue.Body.Producto = Producto;
            inValue.Body.Total = Total;
            inValue.Body.cuentaID = cuentaID;
            inValue.Body.Cedula = Cedula;
            CORE.integracionSR.InsertCuentaINTEGRACIONResponse retVal = ((CORE.integracionSR.integracionSWSoap)(this)).InsertCuentaINTEGRACION(inValue);
            return retVal.Body.InsertCuentaINTEGRACIONResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CORE.integracionSR.InsertCuentaINTEGRACIONResponse> CORE.integracionSR.integracionSWSoap.InsertCuentaINTEGRACIONAsync(CORE.integracionSR.InsertCuentaINTEGRACIONRequest request) {
            return base.Channel.InsertCuentaINTEGRACIONAsync(request);
        }
        
        public System.Threading.Tasks.Task<CORE.integracionSR.InsertCuentaINTEGRACIONResponse> InsertCuentaINTEGRACIONAsync(string Nombres, string Apellidos, string Producto, decimal Total, string cuentaID, string Cedula) {
            CORE.integracionSR.InsertCuentaINTEGRACIONRequest inValue = new CORE.integracionSR.InsertCuentaINTEGRACIONRequest();
            inValue.Body = new CORE.integracionSR.InsertCuentaINTEGRACIONRequestBody();
            inValue.Body.Nombres = Nombres;
            inValue.Body.Apellidos = Apellidos;
            inValue.Body.Producto = Producto;
            inValue.Body.Total = Total;
            inValue.Body.cuentaID = cuentaID;
            inValue.Body.Cedula = Cedula;
            return ((CORE.integracionSR.integracionSWSoap)(this)).InsertCuentaINTEGRACIONAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CORE.integracionSR.DeleteCuentaINTEGRACIONResponse CORE.integracionSR.integracionSWSoap.DeleteCuentaINTEGRACION(CORE.integracionSR.DeleteCuentaINTEGRACIONRequest request) {
            return base.Channel.DeleteCuentaINTEGRACION(request);
        }
        
        public string DeleteCuentaINTEGRACION(string cuentaID) {
            CORE.integracionSR.DeleteCuentaINTEGRACIONRequest inValue = new CORE.integracionSR.DeleteCuentaINTEGRACIONRequest();
            inValue.Body = new CORE.integracionSR.DeleteCuentaINTEGRACIONRequestBody();
            inValue.Body.cuentaID = cuentaID;
            CORE.integracionSR.DeleteCuentaINTEGRACIONResponse retVal = ((CORE.integracionSR.integracionSWSoap)(this)).DeleteCuentaINTEGRACION(inValue);
            return retVal.Body.DeleteCuentaINTEGRACIONResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CORE.integracionSR.DeleteCuentaINTEGRACIONResponse> CORE.integracionSR.integracionSWSoap.DeleteCuentaINTEGRACIONAsync(CORE.integracionSR.DeleteCuentaINTEGRACIONRequest request) {
            return base.Channel.DeleteCuentaINTEGRACIONAsync(request);
        }
        
        public System.Threading.Tasks.Task<CORE.integracionSR.DeleteCuentaINTEGRACIONResponse> DeleteCuentaINTEGRACIONAsync(string cuentaID) {
            CORE.integracionSR.DeleteCuentaINTEGRACIONRequest inValue = new CORE.integracionSR.DeleteCuentaINTEGRACIONRequest();
            inValue.Body = new CORE.integracionSR.DeleteCuentaINTEGRACIONRequestBody();
            inValue.Body.cuentaID = cuentaID;
            return ((CORE.integracionSR.integracionSWSoap)(this)).DeleteCuentaINTEGRACIONAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CORE.integracionSR.InsertFacturaINTEGRACIONResponse CORE.integracionSR.integracionSWSoap.InsertFacturaINTEGRACION(CORE.integracionSR.InsertFacturaINTEGRACIONRequest request) {
            return base.Channel.InsertFacturaINTEGRACION(request);
        }
        
        public string InsertFacturaINTEGRACION(string Nombres, string Apellidos, string Producto, decimal Total, string cuentaID, string Cedula, string facturadoPor) {
            CORE.integracionSR.InsertFacturaINTEGRACIONRequest inValue = new CORE.integracionSR.InsertFacturaINTEGRACIONRequest();
            inValue.Body = new CORE.integracionSR.InsertFacturaINTEGRACIONRequestBody();
            inValue.Body.Nombres = Nombres;
            inValue.Body.Apellidos = Apellidos;
            inValue.Body.Producto = Producto;
            inValue.Body.Total = Total;
            inValue.Body.cuentaID = cuentaID;
            inValue.Body.Cedula = Cedula;
            inValue.Body.facturadoPor = facturadoPor;
            CORE.integracionSR.InsertFacturaINTEGRACIONResponse retVal = ((CORE.integracionSR.integracionSWSoap)(this)).InsertFacturaINTEGRACION(inValue);
            return retVal.Body.InsertFacturaINTEGRACIONResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CORE.integracionSR.InsertFacturaINTEGRACIONResponse> CORE.integracionSR.integracionSWSoap.InsertFacturaINTEGRACIONAsync(CORE.integracionSR.InsertFacturaINTEGRACIONRequest request) {
            return base.Channel.InsertFacturaINTEGRACIONAsync(request);
        }
        
        public System.Threading.Tasks.Task<CORE.integracionSR.InsertFacturaINTEGRACIONResponse> InsertFacturaINTEGRACIONAsync(string Nombres, string Apellidos, string Producto, decimal Total, string cuentaID, string Cedula, string facturadoPor) {
            CORE.integracionSR.InsertFacturaINTEGRACIONRequest inValue = new CORE.integracionSR.InsertFacturaINTEGRACIONRequest();
            inValue.Body = new CORE.integracionSR.InsertFacturaINTEGRACIONRequestBody();
            inValue.Body.Nombres = Nombres;
            inValue.Body.Apellidos = Apellidos;
            inValue.Body.Producto = Producto;
            inValue.Body.Total = Total;
            inValue.Body.cuentaID = cuentaID;
            inValue.Body.Cedula = Cedula;
            inValue.Body.facturadoPor = facturadoPor;
            return ((CORE.integracionSR.integracionSWSoap)(this)).InsertFacturaINTEGRACIONAsync(inValue);
        }
    }
}
